from .audit import AuditMixin as AuditMixin
from .client import (
    Client as Client,
    ClientBase as ClientBase,
    ClientCreate as ClientCreate,
    ClientPublic as ClientPublic,
    ClientsPublic as ClientsPublic,
    ClientUpdate as ClientUpdate,
    Correspondence as Correspondence,
    CorrespondenceBase as CorrespondenceBase,
    CorrespondenceCreate as CorrespondenceCreate,
    CorrespondencePublic as CorrespondencePublic,
    CorrespondencesPublic as CorrespondencesPublic,
    CorrespondenceUpdate as CorrespondenceUpdate,
)
from .policy import (
    Insurer as Insurer,
    InsurerBase as InsurerBase,
    InsurerCreate as InsurerCreate,
    InsurerPublic as InsurerPublic,
    InsurersPublic as InsurersPublic,
    InsurerUpdate as InsurerUpdate,
    Invoice as Invoice,
    InvoiceBase as InvoiceBase,
    InvoiceBulkCreate as InvoiceBulkCreate,
    InvoiceCreate as InvoiceCreate,
    InvoiceLineItem as InvoiceLineItem,
    InvoiceLineItemBase as InvoiceLineItemBase,
    InvoiceLineItemCreate as InvoiceLineItemCreate,
    InvoiceLineItemDetailedPublic as InvoiceLineItemDetailedPublic,
    InvoiceLineItemPublic as InvoiceLineItemPublic,
    InvoicePublic as InvoicePublic,
    InvoicesPublic as InvoicesPublic,
    InvoiceStatus as InvoiceStatus,
    InvoiceUpdate as InvoiceUpdate,
    PoliciesPublic as PoliciesPublic,
    Policy as Policy,
    PolicyBase as PolicyBase,
    PolicyCreate as PolicyCreate,
    PolicyCreateExtended as PolicyCreateExtended,
    PolicyPublic as PolicyPublic,
    PolicyStatus as PolicyStatus,
    PolicyUpdate as PolicyUpdate,
    PricingStrategy as PricingStrategy,
    Product as Product,
    ProductBase as ProductBase,
    ProductCreate as ProductCreate,
    ProductPublic as ProductPublic,
    ProductsPublic as ProductsPublic,
    ProductUpdate as ProductUpdate,
    Receipt as Receipt,
    ReceiptAllocation as ReceiptAllocation,
    ReceiptAllocationBase as ReceiptAllocationBase,
    ReceiptAllocationCreate as ReceiptAllocationCreate,
    ReceiptAllocationsPublic as ReceiptAllocationsPublic,
    ReceiptBase as ReceiptBase,
    ReceiptCreate as ReceiptCreate,
    ReceiptPublic as ReceiptPublic,
    ReceiptsPublic as ReceiptsPublic,
    ReceiptStatus as ReceiptStatus,
    ReceiptUpdate as ReceiptUpdate,
    RiskNote as RiskNote,
    RiskNoteBase as RiskNoteBase,
    RiskNoteCreate as RiskNoteCreate,
    RiskNotePublic as RiskNotePublic,
    RiskNotesPublic as RiskNotesPublic,
    RiskNoteStatus as RiskNoteStatus,
    RiskNoteUpdate as RiskNoteUpdate,
    TransactionType as TransactionType,
)
from .user import (
    Message as Message,
    NewPassword as NewPassword,
    Token as Token,
    TokenPayload as TokenPayload,
    UpdatePassword as UpdatePassword,
    User as User,
    UserBase as UserBase,
    UserCreate as UserCreate,
    UserPublic as UserPublic,
    UserRegister as UserRegister,
    UserRole as UserRole,
    UsersPublic as UsersPublic,
    UserUpdate as UserUpdate,
    UserUpdateMe as UserUpdateMe,
)
from .claim import (
    Claim as Claim,
    ClaimBase as ClaimBase,
    ClaimCreate as ClaimCreate,
    ClaimEvent as ClaimEvent,
    ClaimEventBase as ClaimEventBase,
    ClaimEventCreate as ClaimEventCreate,
    ClaimEventPublic as ClaimEventPublic,
    ClaimEventsPublic as ClaimEventsPublic,
    ClaimPublic as ClaimPublic,
    ClaimsPublic as ClaimsPublic,
    ClaimStatus as ClaimStatus,
    ClaimUpdate as ClaimUpdate,
    ClaimEventType as ClaimEventType,
)
from .document import (
    Document as Document,
    DocumentBase as DocumentBase,
    DocumentCreate as DocumentCreate,
    DocumentEntityType as DocumentEntityType,
    DocumentPublic as DocumentPublic,
    DocumentsPublic as DocumentsPublic,
    DocumentType as DocumentType,
    DocumentUpdate as DocumentUpdate,
)

# Re-run model rebuilds to ensure all cross-module relationships are correctly resolved
Client.model_rebuild()
Policy.model_rebuild()
RiskNote.model_rebuild()
Claim.model_rebuild()
Invoice.model_rebuild()
Receipt.model_rebuild()
