// This file is auto-generated by @hey-api/openapi-ts

export const Body_documents_upload_documentSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        },
        entity_type: {
            type: 'string',
            title: 'Entity Type'
        },
        entity_id: {
            type: 'string',
            format: 'uuid',
            title: 'Entity Id'
        },
        document_type: {
            type: 'string',
            title: 'Document Type'
        },
        metadata_json: {
            type: 'string',
            title: 'Metadata Json',
            default: ''
        }
    },
    type: 'object',
    required: ['file', 'entity_type', 'entity_id', 'document_type'],
    title: 'Body_documents-upload_document'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ClaimCreateSchema = {
    properties: {
        claim_number: {
            type: 'string',
            title: 'Claim Number'
        },
        policy_id: {
            type: 'string',
            format: 'uuid',
            title: 'Policy Id'
        },
        date_of_loss: {
            type: 'string',
            format: 'date',
            title: 'Date Of Loss'
        },
        date_reported: {
            type: 'string',
            format: 'date',
            title: 'Date Reported'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        status: {
            type: 'string',
            title: 'Status',
            default: 'Reported'
        },
        reserve_amount: {
            type: 'number',
            title: 'Reserve Amount',
            default: 0
        }
    },
    type: 'object',
    required: ['claim_number', 'policy_id', 'date_of_loss', 'description'],
    title: 'ClaimCreate'
} as const;

export const ClaimPublicSchema = {
    properties: {
        claim_number: {
            type: 'string',
            title: 'Claim Number'
        },
        policy_id: {
            type: 'string',
            format: 'uuid',
            title: 'Policy Id'
        },
        date_of_loss: {
            type: 'string',
            format: 'date',
            title: 'Date Of Loss'
        },
        date_reported: {
            type: 'string',
            format: 'date',
            title: 'Date Reported'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        status: {
            type: 'string',
            title: 'Status',
            default: 'Reported'
        },
        reserve_amount: {
            type: 'number',
            title: 'Reserve Amount',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['claim_number', 'policy_id', 'date_of_loss', 'description', 'id'],
    title: 'ClaimPublic'
} as const;

export const ClaimUpdateSchema = {
    properties: {
        claim_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Claim Number'
        },
        policy_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Policy Id'
        },
        date_of_loss: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Of Loss'
        },
        date_reported: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Reported'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        reserve_amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reserve Amount'
        }
    },
    type: 'object',
    title: 'ClaimUpdate'
} as const;

export const ClaimsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ClaimPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ClaimsPublic'
} as const;

export const ClientCreateSchema = {
    properties: {
        client_type: {
            type: 'string',
            title: 'Client Type',
            default: 'Individual'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        kra_pin: {
            type: 'string',
            title: 'Kra Pin'
        },
        email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        phone: {
            type: 'string',
            title: 'Phone'
        },
        postal_address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Postal Address'
        },
        contacts: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Contacts'
        }
    },
    type: 'object',
    required: ['name', 'kra_pin', 'phone'],
    title: 'ClientCreate'
} as const;

export const ClientPublicSchema = {
    properties: {
        client_type: {
            type: 'string',
            title: 'Client Type',
            default: 'Individual'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        kra_pin: {
            type: 'string',
            title: 'Kra Pin'
        },
        email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        phone: {
            type: 'string',
            title: 'Phone'
        },
        postal_address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Postal Address'
        },
        contacts: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Contacts'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'kra_pin', 'phone', 'id'],
    title: 'ClientPublic'
} as const;

export const ClientUpdateSchema = {
    properties: {
        client_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Type'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        kra_pin: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Kra Pin'
        },
        email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        postal_address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Postal Address'
        },
        contacts: {
            anyOf: [
                {
                    items: {
                        additionalProperties: true,
                        type: 'object'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contacts'
        }
    },
    type: 'object',
    title: 'ClientUpdate'
} as const;

export const ClientsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ClientPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ClientsPublic'
} as const;

export const CorrespondenceCreateSchema = {
    properties: {
        client_id: {
            type: 'string',
            format: 'uuid',
            title: 'Client Id'
        },
        subject: {
            type: 'string',
            title: 'Subject'
        },
        summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        },
        file_path: {
            type: 'string',
            title: 'File Path'
        },
        date_logged: {
            type: 'string',
            format: 'date-time',
            title: 'Date Logged'
        }
    },
    type: 'object',
    required: ['client_id', 'subject', 'file_path'],
    title: 'CorrespondenceCreate'
} as const;

export const CorrespondencePublicSchema = {
    properties: {
        client_id: {
            type: 'string',
            format: 'uuid',
            title: 'Client Id'
        },
        subject: {
            type: 'string',
            title: 'Subject'
        },
        summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        },
        file_path: {
            type: 'string',
            title: 'File Path'
        },
        date_logged: {
            type: 'string',
            format: 'date-time',
            title: 'Date Logged'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['client_id', 'subject', 'file_path', 'id'],
    title: 'CorrespondencePublic'
} as const;

export const CorrespondencesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CorrespondencePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CorrespondencesPublic'
} as const;

export const DocumentPublicSchema = {
    properties: {
        entity_type: {
            type: 'string',
            title: 'Entity Type'
        },
        entity_id: {
            type: 'string',
            format: 'uuid',
            title: 'Entity Id'
        },
        document_type: {
            type: 'string',
            title: 'Document Type'
        },
        file_path: {
            type: 'string',
            title: 'File Path'
        },
        mime_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mime Type'
        },
        doc_metadata: {
            additionalProperties: true,
            type: 'object',
            title: 'Doc Metadata'
        },
        uploaded_at: {
            type: 'string',
            format: 'date-time',
            title: 'Uploaded At'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['entity_type', 'entity_id', 'document_type', 'file_path', 'id'],
    title: 'DocumentPublic'
} as const;

export const DocumentsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DocumentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DocumentsPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const InsurerCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'InsurerCreate'
} as const;

export const InsurerPublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'InsurerPublic'
} as const;

export const InsurerUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        }
    },
    type: 'object',
    title: 'InsurerUpdate'
} as const;

export const InsurersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/InsurerPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'InsurersPublic'
} as const;

export const InvoiceCreateSchema = {
    properties: {
        invoice_number: {
            type: 'string',
            title: 'Invoice Number'
        },
        client_id: {
            type: 'string',
            format: 'uuid',
            title: 'Client Id'
        },
        date_issued: {
            type: 'string',
            format: 'date',
            title: 'Date Issued'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        status: {
            type: 'string',
            title: 'Status',
            default: 'Unpaid'
        },
        total_amount: {
            type: 'number',
            title: 'Total Amount',
            default: 0
        },
        balance_due: {
            type: 'number',
            title: 'Balance Due',
            default: 0
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['invoice_number', 'client_id'],
    title: 'InvoiceCreate'
} as const;

export const InvoiceLineItemPublicSchema = {
    properties: {
        invoice_id: {
            type: 'string',
            format: 'uuid',
            title: 'Invoice Id'
        },
        risk_note_id: {
            type: 'string',
            format: 'uuid',
            title: 'Risk Note Id'
        },
        amount: {
            type: 'number',
            title: 'Amount'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        risk_note: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/RiskNotePublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['invoice_id', 'risk_note_id', 'amount', 'id'],
    title: 'InvoiceLineItemPublic'
} as const;

export const InvoicePublicSchema = {
    properties: {
        invoice_number: {
            type: 'string',
            title: 'Invoice Number'
        },
        client_id: {
            type: 'string',
            format: 'uuid',
            title: 'Client Id'
        },
        date_issued: {
            type: 'string',
            format: 'date',
            title: 'Date Issued'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        status: {
            type: 'string',
            title: 'Status',
            default: 'Unpaid'
        },
        total_amount: {
            type: 'number',
            title: 'Total Amount',
            default: 0
        },
        balance_due: {
            type: 'number',
            title: 'Balance Due',
            default: 0
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        line_items: {
            items: {
                '$ref': '#/components/schemas/InvoiceLineItemPublic'
            },
            type: 'array',
            title: 'Line Items',
            default: []
        },
        allocations: {
            items: {
                '$ref': '#/components/schemas/ReceiptAllocationBase'
            },
            type: 'array',
            title: 'Allocations',
            default: []
        }
    },
    type: 'object',
    required: ['invoice_number', 'client_id', 'id'],
    title: 'InvoicePublic'
} as const;

export const InvoicesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/InvoicePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'InvoicesPublic'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PoliciesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PolicyPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PoliciesPublic'
} as const;

export const PolicyCreateSchema = {
    properties: {
        policy_number: {
            type: 'string',
            title: 'Policy Number'
        },
        client_id: {
            type: 'string',
            format: 'uuid',
            title: 'Client Id'
        },
        product_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Id'
        },
        status: {
            type: 'string',
            title: 'Status',
            default: 'Active'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        total_premium: {
            type: 'number',
            title: 'Total Premium',
            default: 0
        },
        premium_breakdown: {
            additionalProperties: true,
            type: 'object',
            title: 'Premium Breakdown'
        },
        risk_details: {
            additionalProperties: true,
            type: 'object',
            title: 'Risk Details'
        }
    },
    type: 'object',
    required: ['policy_number', 'client_id'],
    title: 'PolicyCreate'
} as const;

export const PolicyPublicSchema = {
    properties: {
        policy_number: {
            type: 'string',
            title: 'Policy Number'
        },
        client_id: {
            type: 'string',
            format: 'uuid',
            title: 'Client Id'
        },
        product_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Id'
        },
        status: {
            type: 'string',
            title: 'Status',
            default: 'Active'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        total_premium: {
            type: 'number',
            title: 'Total Premium',
            default: 0
        },
        premium_breakdown: {
            additionalProperties: true,
            type: 'object',
            title: 'Premium Breakdown'
        },
        risk_details: {
            additionalProperties: true,
            type: 'object',
            title: 'Risk Details'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        product: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ProductPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        display_name: {
            type: 'string',
            title: 'Display Name',
            readOnly: true
        }
    },
    type: 'object',
    required: ['policy_number', 'client_id', 'id', 'display_name'],
    title: 'PolicyPublic'
} as const;

export const PolicyUpdateSchema = {
    properties: {
        policy_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Policy Number'
        },
        client_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        product_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Id'
        },
        status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        total_premium: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total Premium'
        },
        premium_breakdown: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Premium Breakdown'
        },
        risk_details: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Risk Details'
        }
    },
    type: 'object',
    title: 'PolicyUpdate'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProductCreateSchema = {
    properties: {
        insurer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Insurer Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        class_of_insurance: {
            type: 'string',
            title: 'Class Of Insurance'
        },
        product_details: {
            additionalProperties: true,
            type: 'object',
            title: 'Product Details'
        },
        default_commission_rate: {
            type: 'number',
            title: 'Default Commission Rate',
            default: 10
        }
    },
    type: 'object',
    required: ['insurer_id', 'name', 'class_of_insurance'],
    title: 'ProductCreate'
} as const;

export const ProductPublicSchema = {
    properties: {
        insurer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Insurer Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        class_of_insurance: {
            type: 'string',
            title: 'Class Of Insurance'
        },
        product_details: {
            additionalProperties: true,
            type: 'object',
            title: 'Product Details'
        },
        default_commission_rate: {
            type: 'number',
            title: 'Default Commission Rate',
            default: 10
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        insurer: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/InsurerPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['insurer_id', 'name', 'class_of_insurance', 'id'],
    title: 'ProductPublic'
} as const;

export const ProductUpdateSchema = {
    properties: {
        insurer_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Insurer Id'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        class_of_insurance: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Class Of Insurance'
        },
        product_details: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Details'
        },
        default_commission_rate: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Commission Rate'
        }
    },
    type: 'object',
    title: 'ProductUpdate'
} as const;

export const ProductsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProductPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProductsPublic'
} as const;

export const ReceiptAllocationBaseSchema = {
    properties: {
        receipt_id: {
            type: 'string',
            format: 'uuid',
            title: 'Receipt Id'
        },
        invoice_id: {
            type: 'string',
            format: 'uuid',
            title: 'Invoice Id'
        },
        risk_note_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Risk Note Id'
        },
        amount_allocated: {
            type: 'number',
            title: 'Amount Allocated'
        }
    },
    type: 'object',
    required: ['receipt_id', 'invoice_id', 'amount_allocated'],
    title: 'ReceiptAllocationBase'
} as const;

export const ReceiptAllocationCreateSchema = {
    properties: {
        receipt_id: {
            type: 'string',
            format: 'uuid',
            title: 'Receipt Id'
        },
        invoice_id: {
            type: 'string',
            format: 'uuid',
            title: 'Invoice Id'
        },
        risk_note_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Risk Note Id'
        },
        amount_allocated: {
            type: 'number',
            title: 'Amount Allocated'
        }
    },
    type: 'object',
    required: ['receipt_id', 'invoice_id', 'amount_allocated'],
    title: 'ReceiptAllocationCreate'
} as const;

export const ReceiptCreateSchema = {
    properties: {
        receipt_number: {
            type: 'string',
            title: 'Receipt Number'
        },
        client_id: {
            type: 'string',
            format: 'uuid',
            title: 'Client Id'
        },
        date_received: {
            type: 'string',
            format: 'date',
            title: 'Date Received'
        },
        amount: {
            type: 'number',
            title: 'Amount'
        },
        unallocated_amount: {
            type: 'number',
            title: 'Unallocated Amount',
            default: 0
        },
        mode: {
            type: 'string',
            title: 'Mode'
        },
        reference: {
            type: 'string',
            title: 'Reference'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        status: {
            type: 'string',
            title: 'Status',
            default: 'Active'
        },
        created_by_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created By Id'
        }
    },
    type: 'object',
    required: ['receipt_number', 'client_id', 'date_received', 'amount', 'mode', 'reference'],
    title: 'ReceiptCreate'
} as const;

export const ReceiptPublicSchema = {
    properties: {
        receipt_number: {
            type: 'string',
            title: 'Receipt Number'
        },
        client_id: {
            type: 'string',
            format: 'uuid',
            title: 'Client Id'
        },
        date_received: {
            type: 'string',
            format: 'date',
            title: 'Date Received'
        },
        amount: {
            type: 'number',
            title: 'Amount'
        },
        unallocated_amount: {
            type: 'number',
            title: 'Unallocated Amount',
            default: 0
        },
        mode: {
            type: 'string',
            title: 'Mode'
        },
        reference: {
            type: 'string',
            title: 'Reference'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        status: {
            type: 'string',
            title: 'Status',
            default: 'Active'
        },
        created_by_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created By Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        allocations: {
            items: {
                '$ref': '#/components/schemas/ReceiptAllocationBase'
            },
            type: 'array',
            title: 'Allocations',
            default: []
        }
    },
    type: 'object',
    required: ['receipt_number', 'client_id', 'date_received', 'amount', 'mode', 'reference', 'id'],
    title: 'ReceiptPublic'
} as const;

export const ReceiptsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ReceiptPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ReceiptsPublic'
} as const;

export const RiskNoteCreateSchema = {
    properties: {
        policy_id: {
            type: 'string',
            format: 'uuid',
            title: 'Policy Id'
        },
        transaction_type: {
            type: 'string',
            title: 'Transaction Type'
        },
        status: {
            type: 'string',
            title: 'Status',
            default: 'Draft'
        },
        previous_risk_note_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Previous Risk Note Id'
        },
        invoice_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Invoice Number'
        },
        created_by_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created By Id'
        },
        payment_status: {
            type: 'string',
            title: 'Payment Status',
            default: 'Unpaid'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            type: 'string',
            format: 'date',
            title: 'End Date'
        },
        net_premium: {
            type: 'number',
            title: 'Net Premium'
        },
        taxes: {
            additionalProperties: true,
            type: 'object',
            title: 'Taxes'
        },
        commission_amount: {
            type: 'number',
            title: 'Commission Amount'
        },
        total_amount: {
            type: 'number',
            title: 'Total Amount'
        },
        policy_snapshot: {
            additionalProperties: true,
            type: 'object',
            title: 'Policy Snapshot'
        },
        special_clauses: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Special Clauses'
        }
    },
    type: 'object',
    required: ['policy_id', 'transaction_type', 'start_date', 'end_date', 'net_premium', 'commission_amount', 'total_amount'],
    title: 'RiskNoteCreate'
} as const;

export const RiskNotePublicSchema = {
    properties: {
        policy_id: {
            type: 'string',
            format: 'uuid',
            title: 'Policy Id'
        },
        transaction_type: {
            type: 'string',
            title: 'Transaction Type'
        },
        status: {
            type: 'string',
            title: 'Status',
            default: 'Draft'
        },
        previous_risk_note_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Previous Risk Note Id'
        },
        invoice_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Invoice Number'
        },
        created_by_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created By Id'
        },
        payment_status: {
            type: 'string',
            title: 'Payment Status',
            default: 'Unpaid'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            type: 'string',
            format: 'date',
            title: 'End Date'
        },
        net_premium: {
            type: 'number',
            title: 'Net Premium'
        },
        taxes: {
            additionalProperties: true,
            type: 'object',
            title: 'Taxes'
        },
        commission_amount: {
            type: 'number',
            title: 'Commission Amount'
        },
        total_amount: {
            type: 'number',
            title: 'Total Amount'
        },
        policy_snapshot: {
            additionalProperties: true,
            type: 'object',
            title: 'Policy Snapshot'
        },
        special_clauses: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Special Clauses'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        policy: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PolicyPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['policy_id', 'transaction_type', 'start_date', 'end_date', 'net_premium', 'commission_amount', 'total_amount', 'id'],
    title: 'RiskNotePublic'
} as const;

export const RiskNoteUpdateSchema = {
    properties: {
        transaction_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Transaction Type'
        },
        status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        previous_risk_note_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Previous Risk Note Id'
        },
        invoice_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Invoice Number'
        },
        payment_status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payment Status'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        net_premium: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Net Premium'
        },
        taxes: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Taxes'
        },
        commission_amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Commission Amount'
        },
        total_amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total Amount'
        },
        policy_snapshot: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Policy Snapshot'
        },
        special_clauses: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Special Clauses'
        }
    },
    type: 'object',
    title: 'RiskNoteUpdate'
} as const;

export const RiskNotesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RiskNotePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RiskNotesPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'Viewer'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'Viewer'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserRoleSchema = {
    type: 'string',
    enum: ['Admin', 'Underwriter', 'Cashier', 'Viewer'],
    title: 'UserRole'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'Viewer'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;