// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ClaimCreate = {
    claim_number: string;
    policy_id: string;
    risk_item_id?: (string | null);
    date_of_loss: string;
    description: string;
    status?: string;
    reserve_amount?: number;
};

export type ClaimPublic = {
    claim_number: string;
    policy_id: string;
    risk_item_id?: (string | null);
    date_of_loss: string;
    description: string;
    status?: string;
    reserve_amount?: number;
    id: string;
};

export type ClaimsPublic = {
    data: Array<ClaimPublic>;
    count: number;
};

export type ClaimUpdate = {
    claim_number?: (string | null);
    policy_id?: (string | null);
    risk_item_id?: (string | null);
    date_of_loss?: (string | null);
    description?: (string | null);
    status?: (string | null);
    reserve_amount?: (number | null);
};

export type ClientCreate = {
    client_type?: string;
    name: string;
    kra_pin: string;
    email?: (string | null);
    phone: string;
    physical_address?: (string | null);
    contact_person?: (string | null);
};

export type ClientPublic = {
    client_type?: string;
    name: string;
    kra_pin: string;
    email?: (string | null);
    phone: string;
    physical_address?: (string | null);
    contact_person?: (string | null);
    id: string;
};

export type ClientsPublic = {
    data: Array<ClientPublic>;
    count: number;
};

export type ClientUpdate = {
    client_type?: (string | null);
    name?: (string | null);
    kra_pin?: (string | null);
    email?: (string | null);
    phone?: (string | null);
    physical_address?: (string | null);
    contact_person?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InsurerCreate = {
    name: string;
    email?: (string | null);
    phone?: (string | null);
};

export type InsurerPublic = {
    name: string;
    email?: (string | null);
    phone?: (string | null);
    id: string;
};

export type InsurersPublic = {
    data: Array<InsurerPublic>;
    count: number;
};

export type InsurerUpdate = {
    name?: (string | null);
    email?: (string | null);
    phone?: (string | null);
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PaymentAllocationCreate = {
    payment_id: string;
    risk_note_id: string;
    amount_allocated: number;
};

export type PaymentAllocationPublic = {
    payment_id: string;
    risk_note_id: string;
    amount_allocated: number;
};

export type PaymentCreate = {
    receipt_number: string;
    date_received: string;
    amount: number;
    mode: string;
    reference: string;
};

export type PaymentPublic = {
    receipt_number: string;
    date_received: string;
    amount: number;
    mode: string;
    reference: string;
    id: string;
};

export type PaymentsPublic = {
    data: Array<PaymentPublic>;
    count: number;
};

export type PaymentUpdate = {
    receipt_number?: (string | null);
    date_received?: (string | null);
    amount?: (number | null);
    mode?: (string | null);
    reference?: (string | null);
};

export type PoliciesPublic = {
    data: Array<PolicyPublic>;
    count: number;
};

export type PolicyCreate = {
    policy_number: string;
    client_id: string;
    product_id?: (string | null);
    status?: string;
};

export type PolicyPublic = {
    policy_number: string;
    client_id: string;
    product_id?: (string | null);
    status?: string;
    id: string;
};

export type PolicyUpdate = {
    policy_number?: (string | null);
    client_id?: (string | null);
    product_id?: (string | null);
    status?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProductCreate = {
    insurer_id: string;
    name: string;
    class_of_insurance: string;
    default_benefits?: {
        [key: string]: unknown;
    };
    default_clauses?: Array<(string)>;
    default_commission_rate?: number;
};

export type ProductPublic = {
    insurer_id: string;
    name: string;
    class_of_insurance: string;
    default_benefits?: {
        [key: string]: unknown;
    };
    default_clauses?: Array<(string)>;
    default_commission_rate?: number;
    id: string;
};

export type ProductsPublic = {
    data: Array<ProductPublic>;
    count: number;
};

export type ProductUpdate = {
    insurer_id?: (string | null);
    name?: (string | null);
    class_of_insurance?: (string | null);
    default_benefits?: ({
    [key: string]: unknown;
} | null);
    default_clauses?: (Array<(string)> | null);
    default_commission_rate?: (number | null);
};

export type RiskItemPublic = {
    policy_id: string;
    identifier: string;
    description: string;
    sum_insured: number;
    details?: {
        [key: string]: unknown;
    };
    benefits?: {
        [key: string]: unknown;
    };
    id: string;
};

export type RiskItemsPublic = {
    data: Array<RiskItemPublic>;
    count: number;
};

export type RiskNoteCreate = {
    risk_note_number: string;
    policy_id: string;
    transaction_type: string;
    start_date: string;
    end_date: string;
    basic_premium: number;
    training_levy?: number;
    phcf_levy?: number;
    stamp_duty?: number;
    gross_premium: number;
    commission_amount: number;
    special_clauses?: Array<(string)>;
};

export type RiskNotePublic = {
    risk_note_number: string;
    policy_id: string;
    transaction_type: string;
    start_date: string;
    end_date: string;
    basic_premium: number;
    training_levy?: number;
    phcf_levy?: number;
    stamp_duty?: number;
    gross_premium: number;
    commission_amount: number;
    special_clauses?: Array<(string)>;
    id: string;
};

export type RiskNotesPublic = {
    data: Array<RiskNotePublic>;
    count: number;
};

export type RiskNoteUpdate = {
    risk_note_number?: (string | null);
    transaction_type?: (string | null);
    start_date?: (string | null);
    end_date?: (string | null);
    basic_premium?: (number | null);
    training_levy?: (number | null);
    phcf_levy?: (number | null);
    stamp_duty?: (number | null);
    gross_premium?: (number | null);
    commission_amount?: (number | null);
    special_clauses?: (Array<(string)> | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ClaimsReadClaimsData = {
    limit?: number;
    policyId?: (string | null);
    skip?: number;
};

export type ClaimsReadClaimsResponse = (ClaimsPublic);

export type ClaimsCreateClaimData = {
    requestBody: ClaimCreate;
};

export type ClaimsCreateClaimResponse = (ClaimPublic);

export type ClaimsReadClaimData = {
    id: string;
};

export type ClaimsReadClaimResponse = (ClaimPublic);

export type ClaimsUpdateClaimData = {
    id: string;
    requestBody: ClaimUpdate;
};

export type ClaimsUpdateClaimResponse = (ClaimPublic);

export type ClaimsDeleteClaimData = {
    id: string;
};

export type ClaimsDeleteClaimResponse = (Message);

export type ClientsReadClientsData = {
    limit?: number;
    skip?: number;
};

export type ClientsReadClientsResponse = (ClientsPublic);

export type ClientsCreateClientData = {
    requestBody: ClientCreate;
};

export type ClientsCreateClientResponse = (ClientPublic);

export type ClientsReadClientData = {
    id: string;
};

export type ClientsReadClientResponse = (ClientPublic);

export type ClientsUpdateClientData = {
    id: string;
    requestBody: ClientUpdate;
};

export type ClientsUpdateClientResponse = (ClientPublic);

export type ClientsDeleteClientData = {
    id: string;
};

export type ClientsDeleteClientResponse = (Message);

export type InsurersReadInsurersData = {
    limit?: number;
    skip?: number;
};

export type InsurersReadInsurersResponse = (InsurersPublic);

export type InsurersCreateInsurerData = {
    requestBody: InsurerCreate;
};

export type InsurersCreateInsurerResponse = (InsurerPublic);

export type InsurersReadInsurerData = {
    id: string;
};

export type InsurersReadInsurerResponse = (InsurerPublic);

export type InsurersUpdateInsurerData = {
    id: string;
    requestBody: InsurerUpdate;
};

export type InsurersUpdateInsurerResponse = (InsurerPublic);

export type InsurersDeleteInsurerData = {
    id: string;
};

export type InsurersDeleteInsurerResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PaymentsReadPaymentsData = {
    limit?: number;
    skip?: number;
};

export type PaymentsReadPaymentsResponse = (PaymentsPublic);

export type PaymentsCreatePaymentData = {
    requestBody: PaymentCreate;
};

export type PaymentsCreatePaymentResponse = (PaymentPublic);

export type PaymentsReadPaymentData = {
    id: string;
};

export type PaymentsReadPaymentResponse = (PaymentPublic);

export type PaymentsUpdatePaymentData = {
    id: string;
    requestBody: PaymentUpdate;
};

export type PaymentsUpdatePaymentResponse = (PaymentPublic);

export type PaymentsDeletePaymentData = {
    id: string;
};

export type PaymentsDeletePaymentResponse = (Message);

export type PaymentsCreatePaymentAllocationData = {
    id: string;
    requestBody: PaymentAllocationCreate;
};

export type PaymentsCreatePaymentAllocationResponse = (PaymentAllocationPublic);

export type PoliciesReadPoliciesData = {
    clientId?: (string | null);
    limit?: number;
    skip?: number;
};

export type PoliciesReadPoliciesResponse = (PoliciesPublic);

export type PoliciesCreatePolicyData = {
    requestBody: PolicyCreate;
};

export type PoliciesCreatePolicyResponse = (PolicyPublic);

export type PoliciesReadPolicyData = {
    id: string;
};

export type PoliciesReadPolicyResponse = (PolicyPublic);

export type PoliciesUpdatePolicyData = {
    id: string;
    requestBody: PolicyUpdate;
};

export type PoliciesUpdatePolicyResponse = (PolicyPublic);

export type PoliciesDeletePolicyData = {
    id: string;
};

export type PoliciesDeletePolicyResponse = (Message);

export type PoliciesReadPolicyRiskNotesData = {
    id: string;
};

export type PoliciesReadPolicyRiskNotesResponse = (RiskNotesPublic);

export type PoliciesReadPolicyRiskItemsData = {
    id: string;
};

export type PoliciesReadPolicyRiskItemsResponse = (RiskItemsPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProductsReadProductsData = {
    insurerId?: (string | null);
    limit?: number;
    skip?: number;
};

export type ProductsReadProductsResponse = (ProductsPublic);

export type ProductsCreateProductData = {
    requestBody: ProductCreate;
};

export type ProductsCreateProductResponse = (ProductPublic);

export type ProductsReadProductData = {
    id: string;
};

export type ProductsReadProductResponse = (ProductPublic);

export type ProductsUpdateProductData = {
    id: string;
    requestBody: ProductUpdate;
};

export type ProductsUpdateProductResponse = (ProductPublic);

export type ProductsDeleteProductData = {
    id: string;
};

export type ProductsDeleteProductResponse = (Message);

export type RiskNotesReadRiskNotesData = {
    limit?: number;
    policyId?: (string | null);
    skip?: number;
};

export type RiskNotesReadRiskNotesResponse = (RiskNotesPublic);

export type RiskNotesCreateRiskNoteData = {
    requestBody: RiskNoteCreate;
};

export type RiskNotesCreateRiskNoteResponse = (RiskNotePublic);

export type RiskNotesReadRiskNoteData = {
    id: string;
};

export type RiskNotesReadRiskNoteResponse = (RiskNotePublic);

export type RiskNotesUpdateRiskNoteData = {
    id: string;
    requestBody: RiskNoteUpdate;
};

export type RiskNotesUpdateRiskNoteResponse = (RiskNotePublic);

export type RiskNotesDeleteRiskNoteData = {
    id: string;
};

export type RiskNotesDeleteRiskNoteResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);