// This file is auto-generated by @hey-api/openapi-ts

export type BaseFinancialBreakdown = {
    type?: "base";
    net_premium: string;
    taxes?: {
        [key: string]: (string);
    };
    commission_amount: string;
    total_amount: string;
};

export type BenefitLineItem = {
    name: string;
    amount: string;
};

export type Body_documents_upload_document = {
    file: (Blob | File);
    entity_type: string;
    entity_id: string;
    document_type: string;
    metadata_json?: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ClaimCreate = {
    created_at?: string;
    updated_at?: string;
    deleted_at?: (string | null);
    deleted_by_id?: (string | null);
    claim_number: string;
    policy_id: string;
    date_of_loss: string;
    date_reported?: string;
    description: string;
    status?: ClaimStatus;
    reserve_amount?: (number | string);
};

export type ClaimPublic = {
    created_at?: string;
    updated_at?: string;
    deleted_at?: (string | null);
    deleted_by_id?: (string | null);
    claim_number: string;
    policy_id: string;
    date_of_loss: string;
    date_reported?: string;
    description: string;
    status?: ClaimStatus;
    reserve_amount?: string;
    id: string;
};

export type ClaimsPublic = {
    data: Array<ClaimPublic>;
    count: number;
};

export type ClaimStatus = 'Reported' | 'Assessed' | 'Paid' | 'Rejected' | 'Closed';

export type ClaimUpdate = {
    claim_number?: (string | null);
    policy_id?: (string | null);
    date_of_loss?: (string | null);
    date_reported?: (string | null);
    description?: (string | null);
    status?: (ClaimStatus | null);
    reserve_amount?: (number | string | null);
};

export type ClientCreate = {
    created_at?: string;
    updated_at?: string;
    deleted_at?: (string | null);
    deleted_by_id?: (string | null);
    client_type?: string;
    name: string;
    kra_pin: string;
    email?: (string | null);
    phone: string;
    physical_address?: (string | null);
    postal_number?: (string | null);
    postal_code?: (string | null);
    town?: (string | null);
    contacts?: Array<{
        [key: string]: unknown;
    }>;
};

export type ClientPublic = {
    created_at?: string;
    updated_at?: string;
    deleted_at?: (string | null);
    deleted_by_id?: (string | null);
    client_type?: string;
    name: string;
    kra_pin: string;
    email?: (string | null);
    phone: string;
    physical_address?: (string | null);
    postal_number?: (string | null);
    postal_code?: (string | null);
    town?: (string | null);
    contacts?: Array<{
        [key: string]: unknown;
    }>;
    id: string;
};

export type ClientsPublic = {
    data: Array<ClientPublic>;
    count: number;
};

export type ClientUpdate = {
    client_type?: (string | null);
    name?: (string | null);
    kra_pin?: (string | null);
    email?: (string | null);
    phone?: (string | null);
    physical_address?: (string | null);
    postal_number?: (string | null);
    postal_code?: (string | null);
    town?: (string | null);
    contacts?: (Array<{
    [key: string]: unknown;
}> | null);
};

export type CorrespondenceCreate = {
    created_at?: string;
    updated_at?: string;
    deleted_at?: (string | null);
    deleted_by_id?: (string | null);
    client_id: string;
    subject: string;
    summary?: (string | null);
    file_path: string;
    date_logged?: string;
};

export type CorrespondencePublic = {
    created_at?: string;
    updated_at?: string;
    deleted_at?: (string | null);
    deleted_by_id?: (string | null);
    client_id: string;
    subject: string;
    summary?: (string | null);
    file_path: string;
    date_logged?: string;
    id: string;
};

export type CorrespondencesPublic = {
    data: Array<CorrespondencePublic>;
    count: number;
};

export type DocumentEntityType = 'Client' | 'Policy' | 'Claim' | 'User' | 'RiskNote';

export type DocumentPublic = {
    document_type: DocumentType;
    file_path: string;
    mime_type?: (string | null);
    uploaded_at?: string;
    id: string;
    entity_type: DocumentEntityType;
    entity_id: string;
    doc_metadata?: {
        [key: string]: unknown;
    };
};

export type DocumentsPublic = {
    data: Array<DocumentPublic>;
    count: number;
};

export type DocumentType = 'Logbook' | 'ID' | 'Valuation' | 'PoliceAbstract' | 'Receipt' | 'Other';

export type EndorsementCreate = {
    updated_risk_details: {
        [key: string]: unknown;
    };
    change_description: string;
    effective_date?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InsurerCreate = {
    created_at?: string;
    updated_at?: string;
    deleted_at?: (string | null);
    deleted_by_id?: (string | null);
    name: string;
    email?: (string | null);
    phone?: (string | null);
};

export type InsurerPublic = {
    created_at?: string;
    updated_at?: string;
    deleted_at?: (string | null);
    deleted_by_id?: (string | null);
    name: string;
    email?: (string | null);
    phone?: (string | null);
    id: string;
};

export type InsurersPublic = {
    data: Array<InsurerPublic>;
    count: number;
};

export type InsurerUpdate = {
    name?: (string | null);
    email?: (string | null);
    phone?: (string | null);
};

export type InvoiceBulkCreate = {
    client_id: string;
    risk_note_ids: Array<(string)>;
    date_issued?: string;
    notes?: (string | null);
};

export type InvoiceCreate = {
    created_at?: string;
    updated_at?: string;
    deleted_at?: (string | null);
    deleted_by_id?: (string | null);
    invoice_number: string;
    client_id: string;
    date_issued?: string;
    due_date?: (string | null);
    status?: InvoiceStatus;
    total_amount?: (number | string);
    balance_due?: (number | string);
    notes?: (string | null);
};

export type InvoiceLineItemPublic = {
    invoice_id: string;
    risk_note_id: string;
    amount: string;
    description?: (string | null);
    id: string;
    risk_note?: (RiskNotePublic | null);
};

export type InvoicePublic = {
    created_at?: string;
    updated_at?: string;
    deleted_at?: (string | null);
    deleted_by_id?: (string | null);
    invoice_number: string;
    client_id: string;
    date_issued?: string;
    due_date?: (string | null);
    status?: InvoiceStatus;
    total_amount?: string;
    balance_due?: string;
    notes?: (string | null);
    id: string;
    line_items?: Array<InvoiceLineItemPublic>;
    allocations?: Array<ReceiptAllocationBase>;
};

export type InvoicesPublic = {
    data: Array<InvoicePublic>;
    count: number;
};

export type InvoiceStatus = 'Unpaid' | 'Partial' | 'Paid' | 'Cancelled';

export type Message = {
    message: string;
};

export type MotorFinancialBreakdown = {
    type?: "motor";
    net_premium: string;
    taxes?: {
        [key: string]: (string);
    };
    commission_amount: string;
    total_amount: string;
    benefits?: Array<BenefitLineItem>;
    basic_rate?: (string | null);
    is_high_end?: boolean;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PoliciesPublic = {
    data: Array<PolicyPublic>;
    count: number;
};

export type PolicyCreateExtended = {
    created_at?: string;
    updated_at?: string;
    deleted_at?: (string | null);
    deleted_by_id?: (string | null);
    policy_number: string;
    client_id: string;
    product_id?: (string | null);
    status?: PolicyStatus;
    inception_date?: string;
    coverage_start?: string;
    coverage_end: string;
};

export type PolicyPublic = {
    created_at?: string;
    updated_at?: string;
    deleted_at?: (string | null);
    deleted_by_id?: (string | null);
    policy_number: string;
    client_id: string;
    product_id?: (string | null);
    status?: PolicyStatus;
    inception_date?: string;
    id: string;
    product?: (ProductPublic | null);
    active_note?: (RiskNotePublic | null);
};

export type PolicyStatus = 'Active' | 'Expired' | 'Cancelled' | 'Lapsed';

export type PolicyUpdate = {
    policy_number?: (string | null);
    client_id?: (string | null);
    product_id?: (string | null);
    status?: (PolicyStatus | null);
    inception_date?: (string | null);
};

export type PricingStrategy = 'Percentage' | 'FixedTiered' | 'Manual';

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProductCreate = {
    created_at?: string;
    updated_at?: string;
    deleted_at?: (string | null);
    deleted_by_id?: (string | null);
    insurer_id: string;
    name: string;
    class_of_insurance: string;
    product_details?: {
        [key: string]: unknown;
    };
    pricing_strategy?: PricingStrategy;
    pricing_rules?: {
        [key: string]: unknown;
    };
    default_commission_rate?: number;
    default_benefits_and_limits?: (string | null);
    default_excesses?: (string | null);
    default_special_clauses?: (string | null);
};

export type ProductPublic = {
    created_at?: string;
    updated_at?: string;
    deleted_at?: (string | null);
    deleted_by_id?: (string | null);
    insurer_id: string;
    name: string;
    class_of_insurance: string;
    product_details?: {
        [key: string]: unknown;
    };
    pricing_strategy?: PricingStrategy;
    pricing_rules?: {
        [key: string]: unknown;
    };
    default_commission_rate?: number;
    default_benefits_and_limits?: (string | null);
    default_excesses?: (string | null);
    default_special_clauses?: (string | null);
    id: string;
    insurer?: (InsurerPublic | null);
};

export type ProductsPublic = {
    data: Array<ProductPublic>;
    count: number;
};

export type ProductUpdate = {
    insurer_id?: (string | null);
    name?: (string | null);
    class_of_insurance?: (string | null);
    product_details?: ({
    [key: string]: unknown;
} | null);
    pricing_strategy?: (PricingStrategy | null);
    pricing_rules?: ({
    [key: string]: unknown;
} | null);
    default_commission_rate?: (number | null);
};

export type QuoteRequest = {
    product_id: string;
    risk_details: {
        [key: string]: unknown;
    };
};

export type QuoteResponse = {
    breakdown: (MotorFinancialBreakdown | BaseFinancialBreakdown);
};

export type ReceiptAllocationBase = {
    receipt_id: string;
    invoice_id: string;
    risk_note_id?: (string | null);
    amount_allocated: string;
};

export type ReceiptAllocationCreate = {
    receipt_id: string;
    invoice_id: string;
    risk_note_id?: (string | null);
    amount_allocated: (number | string);
};

export type ReceiptCreate = {
    created_at?: string;
    updated_at?: string;
    deleted_at?: (string | null);
    deleted_by_id?: (string | null);
    receipt_number: string;
    client_id: string;
    date_received: string;
    amount: (number | string);
    unallocated_amount?: (number | string);
    mode: string;
    reference: string;
    notes?: (string | null);
    status?: ReceiptStatus;
    created_by_id?: (string | null);
};

export type ReceiptPublic = {
    created_at?: string;
    updated_at?: string;
    deleted_at?: (string | null);
    deleted_by_id?: (string | null);
    receipt_number: string;
    client_id: string;
    date_received: string;
    amount: string;
    unallocated_amount?: string;
    mode: string;
    reference: string;
    notes?: (string | null);
    status?: ReceiptStatus;
    created_by_id?: (string | null);
    id: string;
    allocations?: Array<ReceiptAllocationBase>;
};

export type ReceiptsPublic = {
    data: Array<ReceiptPublic>;
    count: number;
};

export type ReceiptStatus = 'Active' | 'Voided';

export type RiskNoteCreate = {
    created_at?: string;
    updated_at?: string;
    deleted_at?: (string | null);
    deleted_by_id?: (string | null);
    policy_id: string;
    risk_note_number?: (string | null);
    transaction_type: TransactionType;
    status?: RiskNoteStatus;
    previous_risk_note_id?: (string | null);
    invoice_number?: (string | null);
    created_by_id?: (string | null);
    effective_date?: string;
    coverage_start: string;
    coverage_end: string;
    net_premium: (number | string);
    commission_amount: (number | string);
    total_amount: (number | string);
    cover_snapshot?: {
        [key: string]: unknown;
    };
    financial_breakdown?: {
        [key: string]: unknown;
    };
    special_clauses?: Array<(string)>;
};

export type RiskNotePublic = {
    created_at?: string;
    updated_at?: string;
    deleted_at?: (string | null);
    deleted_by_id?: (string | null);
    policy_id: string;
    risk_note_number?: (string | null);
    transaction_type: TransactionType;
    status?: RiskNoteStatus;
    previous_risk_note_id?: (string | null);
    invoice_number?: (string | null);
    created_by_id?: (string | null);
    effective_date?: string;
    coverage_start: string;
    coverage_end: string;
    net_premium: string;
    commission_amount: string;
    total_amount: string;
    cover_snapshot?: {
        [key: string]: unknown;
    };
    id: string;
    policy?: (PolicyPublic | null);
    financial_breakdown?: {
        [key: string]: unknown;
    };
    special_clauses?: Array<(string)>;
};

export type RiskNotesPublic = {
    data: Array<RiskNotePublic>;
    count: number;
};

export type RiskNoteStatus = 'Draft' | 'Issued' | 'Replaced' | 'Cancelled';

export type RiskNoteUpdate = {
    transaction_type?: (TransactionType | null);
    risk_note_number?: (string | null);
    status?: (RiskNoteStatus | null);
    previous_risk_note_id?: (string | null);
    invoice_number?: (string | null);
    effective_date?: (string | null);
    coverage_start?: (string | null);
    coverage_end?: (string | null);
    net_premium?: (number | string | null);
    financial_breakdown?: ({
    [key: string]: unknown;
} | null);
    commission_amount?: (number | string | null);
    total_amount?: (number | string | null);
    special_clauses?: (Array<(string)> | null);
    cover_snapshot?: ({
    [key: string]: unknown;
} | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TransactionType = 'New Business' | 'Renewal' | 'Endorsement' | 'Cancellation';

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserRole = 'Admin' | 'Underwriter' | 'Cashier' | 'Viewer';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ClaimsReadClaimsData = {
    limit?: number;
    policyId?: (string | null);
    skip?: number;
};

export type ClaimsReadClaimsResponse = (ClaimsPublic);

export type ClaimsCreateClaimData = {
    requestBody: ClaimCreate;
};

export type ClaimsCreateClaimResponse = (ClaimPublic);

export type ClaimsReadClaimData = {
    id: string;
};

export type ClaimsReadClaimResponse = (ClaimPublic);

export type ClaimsUpdateClaimData = {
    id: string;
    requestBody: ClaimUpdate;
};

export type ClaimsUpdateClaimResponse = (ClaimPublic);

export type ClaimsDeleteClaimData = {
    id: string;
};

export type ClaimsDeleteClaimResponse = (Message);

export type ClientsReadClientsData = {
    limit?: number;
    skip?: number;
};

export type ClientsReadClientsResponse = (ClientsPublic);

export type ClientsCreateClientData = {
    requestBody: ClientCreate;
};

export type ClientsCreateClientResponse = (ClientPublic);

export type ClientsReadClientData = {
    id: string;
};

export type ClientsReadClientResponse = (ClientPublic);

export type ClientsUpdateClientData = {
    id: string;
    requestBody: ClientUpdate;
};

export type ClientsUpdateClientResponse = (ClientPublic);

export type ClientsDeleteClientData = {
    id: string;
};

export type ClientsDeleteClientResponse = (Message);

export type ClientsReadClientCorrespondencesData = {
    id: string;
};

export type ClientsReadClientCorrespondencesResponse = (CorrespondencesPublic);

export type ClientsCreateClientCorrespondenceData = {
    id: string;
    requestBody: CorrespondenceCreate;
};

export type ClientsCreateClientCorrespondenceResponse = (CorrespondencePublic);

export type DocumentsReadDocumentsData = {
    entityId?: (string | null);
    entityType?: (string | null);
    limit?: number;
    skip?: number;
};

export type DocumentsReadDocumentsResponse = (DocumentsPublic);

export type DocumentsUploadDocumentData = {
    formData: Body_documents_upload_document;
};

export type DocumentsUploadDocumentResponse = (DocumentPublic);

export type DocumentsReadDocumentByIdData = {
    id: string;
};

export type DocumentsReadDocumentByIdResponse = (DocumentPublic);

export type DocumentsRemoveDocumentData = {
    id: string;
};

export type DocumentsRemoveDocumentResponse = (DocumentPublic);

export type DocumentsDownloadDocumentData = {
    id: string;
};

export type DocumentsDownloadDocumentResponse = (unknown);

export type FinancialsReadInvoicesData = {
    clientId?: (string | null);
    limit?: number;
    skip?: number;
};

export type FinancialsReadInvoicesResponse = (InvoicesPublic);

export type FinancialsCreateNewInvoiceData = {
    requestBody: InvoiceCreate;
};

export type FinancialsCreateNewInvoiceResponse = (InvoicePublic);

export type FinancialsReadInvoiceData = {
    id: string;
};

export type FinancialsReadInvoiceResponse = (InvoicePublic);

export type FinancialsCreateBulkInvoiceData = {
    requestBody: InvoiceBulkCreate;
};

export type FinancialsCreateBulkInvoiceResponse = (InvoicePublic);

export type FinancialsReadReceiptsData = {
    clientId?: (string | null);
    limit?: number;
    skip?: number;
};

export type FinancialsReadReceiptsResponse = (ReceiptsPublic);

export type FinancialsCreateNewReceiptData = {
    requestBody: ReceiptCreate;
};

export type FinancialsCreateNewReceiptResponse = (ReceiptPublic);

export type FinancialsReadReceiptByIdData = {
    id: string;
};

export type FinancialsReadReceiptByIdResponse = (ReceiptPublic);

export type FinancialsDeleteReceiptData = {
    id: string;
};

export type FinancialsDeleteReceiptResponse = (ReceiptPublic);

export type FinancialsAllocateReceiptData = {
    id: string;
    requestBody: ReceiptAllocationCreate;
};

export type FinancialsAllocateReceiptResponse = (Message);

export type InsurersReadInsurersData = {
    limit?: number;
    skip?: number;
};

export type InsurersReadInsurersResponse = (InsurersPublic);

export type InsurersCreateInsurerData = {
    requestBody: InsurerCreate;
};

export type InsurersCreateInsurerResponse = (InsurerPublic);

export type InsurersReadInsurerData = {
    id: string;
};

export type InsurersReadInsurerResponse = (InsurerPublic);

export type InsurersUpdateInsurerData = {
    id: string;
    requestBody: InsurerUpdate;
};

export type InsurersUpdateInsurerResponse = (InsurerPublic);

export type InsurersDeleteInsurerData = {
    id: string;
};

export type InsurersDeleteInsurerResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PoliciesReadPoliciesData = {
    clientId?: (string | null);
    limit?: number;
    skip?: number;
};

export type PoliciesReadPoliciesResponse = (PoliciesPublic);

export type PoliciesCreatePolicyData = {
    requestBody: PolicyCreateExtended;
};

export type PoliciesCreatePolicyResponse = (PolicyPublic);

export type PoliciesReadPolicyData = {
    id: string;
};

export type PoliciesReadPolicyResponse = (PolicyPublic);

export type PoliciesUpdatePolicyData = {
    id: string;
    requestBody: PolicyUpdate;
};

export type PoliciesUpdatePolicyResponse = (PolicyPublic);

export type PoliciesDeletePolicyData = {
    id: string;
};

export type PoliciesDeletePolicyResponse = (Message);

export type PoliciesGetPolicyQuoteData = {
    requestBody: QuoteRequest;
};

export type PoliciesGetPolicyQuoteResponse = (QuoteResponse);

export type PoliciesCreateEndorsementData = {
    id: string;
    requestBody: EndorsementCreate;
};

export type PoliciesCreateEndorsementResponse = (RiskNotePublic);

export type PoliciesReadPolicyRiskNotesData = {
    id: string;
};

export type PoliciesReadPolicyRiskNotesResponse = (RiskNotesPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProductsReadProductsData = {
    insurerId?: (string | null);
    limit?: number;
    skip?: number;
};

export type ProductsReadProductsResponse = (ProductsPublic);

export type ProductsCreateProductData = {
    requestBody: ProductCreate;
};

export type ProductsCreateProductResponse = (ProductPublic);

export type ProductsReadProductData = {
    id: string;
};

export type ProductsReadProductResponse = (ProductPublic);

export type ProductsUpdateProductData = {
    id: string;
    requestBody: ProductUpdate;
};

export type ProductsUpdateProductResponse = (ProductPublic);

export type ProductsDeleteProductData = {
    id: string;
};

export type ProductsDeleteProductResponse = (Message);

export type RiskNotesReadRiskNotesData = {
    clientId?: (string | null);
    limit?: number;
    policyId?: (string | null);
    skip?: number;
    uninvoicedOnly?: boolean;
};

export type RiskNotesReadRiskNotesResponse = (RiskNotesPublic);

export type RiskNotesCreateRiskNoteData = {
    requestBody: RiskNoteCreate;
};

export type RiskNotesCreateRiskNoteResponse = (RiskNotePublic);

export type RiskNotesReadRiskNoteData = {
    id: string;
};

export type RiskNotesReadRiskNoteResponse = (RiskNotePublic);

export type RiskNotesUpdateRiskNoteData = {
    id: string;
    requestBody: RiskNoteUpdate;
};

export type RiskNotesUpdateRiskNoteResponse = (RiskNotePublic);

export type RiskNotesDeleteRiskNoteData = {
    id: string;
};

export type RiskNotesDeleteRiskNoteResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);