from .insurance.catalog import (
    create_insurer,
    create_product,
    get_insurer_by_name,
    get_product_by_name,
    update_insurer,
    update_product,
)
from .insurance.client import (
    create_client,
    create_correspondence,
    get_client_by_email,
    get_client_by_kra_pin,
    update_client,
    update_correspondence,
)
from .insurance.payment import (
    create_payment,
    create_payment_allocation,
    get_payment_by_receipt_number,
    update_payment,
    update_payment_allocation,
)
from .insurance.policy import (
    create_claim,
    create_policy,
    create_policy_document,
    create_risk_item,
    create_risk_note,
    get_policies_by_client_id,
    get_policy_by_policy_number,
    get_risk_item_by_identifier,
    update_claim,
    update_policy,
    update_policy_document,
    update_risk_item,
    update_risk_note,
)
from .item import create_item
from .user import authenticate, create_user, get_user_by_email, update_user

__all__ = [
    "create_item",
    "authenticate",
    "create_user",
    "get_user_by_email",
    "update_user",
    "create_insurer",
    "get_insurer_by_name",
    "create_product",
    "get_product_by_name",
    "update_insurer",
    "update_product",
    "create_client",
    "get_client_by_kra_pin",
    "get_client_by_email",
    "update_client",
    "create_correspondence",
    "update_correspondence",
    "create_payment",
    "get_payment_by_receipt_number",
    "update_payment",
    "create_payment_allocation",
    "update_payment_allocation",
    "create_policy",
    "get_policy_by_policy_number",
    "get_policies_by_client_id",
    "update_policy",
    "create_risk_item",
    "get_risk_item_by_identifier",
    "update_risk_item",
    "create_risk_note",
    "update_risk_note",
    "create_claim",
    "update_claim",
    "create_policy_document",
    "update_policy_document",
]
