"""Add status to RiskNote

Revision ID: 062485cdd4fd
Revises: d2009cd3d8cc
Create Date: 2026-01-30 10:06:27.636834

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '062485cdd4fd'
down_revision = 'd2009cd3d8cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risknote', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE risknote SET status = 'Active'")
    op.alter_column('risknote', 'status', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risknote', 'status')
    # ### end Alembic commands ###
