"""restore_product_details_schema

Revision ID: 067034ce2c0b
Revises: 062485cdd4fd
Create Date: 2026-01-30 12:27:37.678745

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '067034ce2c0b'
down_revision = '062485cdd4fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_details', sa.JSON(), nullable=False))
    op.drop_column('product', 'default_benefits')
    op.drop_column('product', 'default_clauses')
    op.drop_column('product', 'pricing_strategy')
    op.drop_column('product', 'pricing_rules')
    op.drop_column('product', 'form_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('form_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('pricing_rules', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('pricing_strategy', postgresql.ENUM('PERCENTAGE', 'FIXED_TIERED', 'MANUAL', name='pricingstrategy'), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('default_clauses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('default_benefits', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('product', 'product_details')
    # ### end Alembic commands ###
