"""refactor financial models

Revision ID: 0774676eff5c
Revises: b1fcc5550935
Create Date: 2026-01-28 11:06:57.846668

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0774676eff5c'
down_revision = 'b1fcc5550935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('date_issued', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('balance_due', sa.Float(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_invoice_number'), 'invoice', ['invoice_number'], unique=True)
    op.create_table('receipt',
    sa.Column('receipt_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('date_received', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_receipt_number'), 'receipt', ['receipt_number'], unique=True)
    op.create_table('receiptallocation',
    sa.Column('receipt_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('amount_allocated', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoicelineitem',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('risk_note_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['risk_note_id'], ['risknote.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('paymentallocation')
    op.drop_table('payment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('receipt_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_received', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('mode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reference', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='payment_pkey'),
    sa.UniqueConstraint('receipt_number', name='payment_receipt_number_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('paymentallocation',
    sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('risk_note_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount_allocated', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name=op.f('paymentallocation_payment_id_fkey')),
    sa.ForeignKeyConstraint(['risk_note_id'], ['risknote.id'], name=op.f('paymentallocation_risk_note_id_fkey')),
    sa.PrimaryKeyConstraint('payment_id', 'risk_note_id', name=op.f('paymentallocation_pkey'))
    )
    op.drop_table('invoicelineitem')
    op.drop_table('receiptallocation')
    op.drop_index(op.f('ix_receipt_receipt_number'), table_name='receipt')
    op.drop_table('receipt')
    op.drop_index(op.f('ix_invoice_invoice_number'), table_name='invoice')
    op.drop_table('invoice')
    # ### end Alembic commands ###
