"""Rename postal_address to postal_number

Revision ID: 1a377ea2e2f3
Revises: ed0f67e684f7
Create Date: 2026-02-09 07:03:44.424750

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1a377ea2e2f3'
down_revision = 'ed0f67e684f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'postal_address', new_column_name='postal_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'postal_number', new_column_name='postal_address')
    # ### end Alembic commands ###
