"""Add indexes for foreign keys

Revision ID: 26421f10e85b
Revises: c9be6269c828
Create Date: 2026-02-13 11:46:50.040652

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '26421f10e85b'
down_revision = 'c9be6269c828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_claim_deleted_by_id'), 'claim', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_claim_policy_id'), 'claim', ['policy_id'], unique=False)
    op.create_index(op.f('ix_claimevent_claim_id'), 'claimevent', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claimevent_created_by_id'), 'claimevent', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_client_deleted_by_id'), 'client', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_correspondence_client_id'), 'correspondence', ['client_id'], unique=False)
    op.create_index(op.f('ix_correspondence_deleted_by_id'), 'correspondence', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_document_entity_id'), 'document', ['entity_id'], unique=False)
    op.create_index(op.f('ix_insurer_deleted_by_id'), 'insurer', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_invoice_client_id'), 'invoice', ['client_id'], unique=False)
    op.create_index(op.f('ix_invoice_deleted_by_id'), 'invoice', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_invoicelineitem_invoice_id'), 'invoicelineitem', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoicelineitem_risk_note_id'), 'invoicelineitem', ['risk_note_id'], unique=False)
    op.create_index(op.f('ix_item_deleted_by_id'), 'item', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_policy_client_id'), 'policy', ['client_id'], unique=False)
    op.create_index(op.f('ix_policy_deleted_by_id'), 'policy', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_policy_product_id'), 'policy', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_deleted_by_id'), 'product', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_product_insurer_id'), 'product', ['insurer_id'], unique=False)
    op.create_index(op.f('ix_receipt_client_id'), 'receipt', ['client_id'], unique=False)
    op.create_index(op.f('ix_receipt_created_by_id'), 'receipt', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_receipt_deleted_by_id'), 'receipt', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_receiptallocation_invoice_id'), 'receiptallocation', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_receiptallocation_receipt_id'), 'receiptallocation', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_receiptallocation_risk_note_id'), 'receiptallocation', ['risk_note_id'], unique=False)
    op.create_index(op.f('ix_risknote_created_by_id'), 'risknote', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_risknote_deleted_by_id'), 'risknote', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_risknote_policy_id'), 'risknote', ['policy_id'], unique=False)
    op.create_index(op.f('ix_risknote_previous_risk_note_id'), 'risknote', ['previous_risk_note_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risknote_previous_risk_note_id'), table_name='risknote')
    op.drop_index(op.f('ix_risknote_policy_id'), table_name='risknote')
    op.drop_index(op.f('ix_risknote_deleted_by_id'), table_name='risknote')
    op.drop_index(op.f('ix_risknote_created_by_id'), table_name='risknote')
    op.drop_index(op.f('ix_receiptallocation_risk_note_id'), table_name='receiptallocation')
    op.drop_index(op.f('ix_receiptallocation_receipt_id'), table_name='receiptallocation')
    op.drop_index(op.f('ix_receiptallocation_invoice_id'), table_name='receiptallocation')
    op.drop_index(op.f('ix_receipt_deleted_by_id'), table_name='receipt')
    op.drop_index(op.f('ix_receipt_created_by_id'), table_name='receipt')
    op.drop_index(op.f('ix_receipt_client_id'), table_name='receipt')
    op.drop_index(op.f('ix_product_insurer_id'), table_name='product')
    op.drop_index(op.f('ix_product_deleted_by_id'), table_name='product')
    op.drop_index(op.f('ix_policy_product_id'), table_name='policy')
    op.drop_index(op.f('ix_policy_deleted_by_id'), table_name='policy')
    op.drop_index(op.f('ix_policy_client_id'), table_name='policy')
    op.drop_index(op.f('ix_item_deleted_by_id'), table_name='item')
    op.drop_index(op.f('ix_invoicelineitem_risk_note_id'), table_name='invoicelineitem')
    op.drop_index(op.f('ix_invoicelineitem_invoice_id'), table_name='invoicelineitem')
    op.drop_index(op.f('ix_invoice_deleted_by_id'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_client_id'), table_name='invoice')
    op.drop_index(op.f('ix_insurer_deleted_by_id'), table_name='insurer')
    op.drop_index(op.f('ix_document_entity_id'), table_name='document')
    op.drop_index(op.f('ix_correspondence_deleted_by_id'), table_name='correspondence')
    op.drop_index(op.f('ix_correspondence_client_id'), table_name='correspondence')
    op.drop_index(op.f('ix_client_deleted_by_id'), table_name='client')
    op.drop_index(op.f('ix_claimevent_created_by_id'), table_name='claimevent')
    op.drop_index(op.f('ix_claimevent_claim_id'), table_name='claimevent')
    op.drop_index(op.f('ix_claim_policy_id'), table_name='claim')
    op.drop_index(op.f('ix_claim_deleted_by_id'), table_name='claim')
    # ### end Alembic commands ###
