"""simplify_insurance_models

Revision ID: 300464e5e502
Revises: 067034ce2c0b
Create Date: 2026-02-06 11:34:41.653028

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '300464e5e502'
down_revision = '067034ce2c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('claim_risk_item_id_fkey'), 'claim', type_='foreignkey')
    op.drop_column('claim', 'risk_item_id')
    op.drop_table('riskitem')
    
    op.add_column('policy', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('policy', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('policy', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Add as nullable first
    op.add_column('policy', sa.Column('total_premium', sa.Float(), nullable=True))
    op.add_column('policy', sa.Column('premium_breakdown', sa.JSON(), nullable=True))
    op.add_column('policy', sa.Column('risk_details', sa.JSON(), nullable=True))
    op.add_column('risknote', sa.Column('policy_snapshot', sa.JSON(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE policy SET total_premium = 0 WHERE total_premium IS NULL")
    op.execute("UPDATE policy SET premium_breakdown = '{}' WHERE premium_breakdown IS NULL")
    op.execute("UPDATE policy SET risk_details = '{}' WHERE risk_details IS NULL")
    op.execute("UPDATE risknote SET policy_snapshot = '{}' WHERE policy_snapshot IS NULL")
    
    # Now set NOT NULL
    op.alter_column('policy', 'total_premium', nullable=False)
    op.alter_column('policy', 'premium_breakdown', nullable=False)
    op.alter_column('policy', 'risk_details', nullable=False)
    op.alter_column('risknote', 'policy_snapshot', nullable=False)
    
    op.drop_column('risknote', 'items_snapshot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risknote', sa.Column('items_snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('risknote', 'policy_snapshot')
    op.drop_column('policy', 'risk_details')
    op.drop_column('policy', 'premium_breakdown')
    op.drop_column('policy', 'total_premium')
    op.drop_column('policy', 'description')
    op.drop_column('policy', 'end_date')
    op.drop_column('policy', 'start_date')

    op.create_table('riskitem',
    sa.Column('policy_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valid_from', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('cover_description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_premium', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('premium_breakdown', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('risk_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('valid_to', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.id'], name=op.f('riskitem_policy_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('riskitem_pkey'))
    )
    op.add_column('claim', sa.Column('risk_item_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('claim_risk_item_id_fkey'), 'claim', 'riskitem', ['risk_item_id'], ['id'])
    # ### end Alembic commands ###
