"""add_physical_address_to_client

Revision ID: 38cad97ed24a
Revises: 78cb7d6ae496
Create Date: 2026-02-18 15:50:14.276642

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '38cad97ed24a'
down_revision = '78cb7d6ae496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('physical_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'physical_address')
    # ### end Alembic commands ###
