"""Refactor document model with single table

Revision ID: 540358348e97
Revises: 26421f10e85b
Create Date: 2026-02-13 12:20:25.713379

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '540358348e97'
down_revision = '26421f10e85b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('client_id', sa.Uuid(), nullable=True))
    op.add_column('document', sa.Column('policy_id', sa.Uuid(), nullable=True))
    op.add_column('document', sa.Column('claim_id', sa.Uuid(), nullable=True))
    op.add_column('document', sa.Column('risk_note_id', sa.Uuid(), nullable=True))
    op.alter_column('document', 'doc_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.create_index(op.f('ix_document_claim_id'), 'document', ['claim_id'], unique=False)
    op.create_index(op.f('ix_document_client_id'), 'document', ['client_id'], unique=False)
    op.create_index(op.f('ix_document_entity_type'), 'document', ['entity_type'], unique=False)
    op.create_index(op.f('ix_document_policy_id'), 'document', ['policy_id'], unique=False)
    op.create_index(op.f('ix_document_risk_note_id'), 'document', ['risk_note_id'], unique=False)
    op.create_foreign_key(None, 'document', 'risknote', ['risk_note_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'document', 'policy', ['policy_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'document', 'claim', ['claim_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'document', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    op.alter_column('policy', 'premium_breakdown',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('policy', 'risk_details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('risknote', 'taxes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('risknote', 'policy_snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('risknote', 'special_clauses',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('risknote', 'special_clauses',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('risknote', 'policy_snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('risknote', 'taxes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('policy', 'risk_details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('policy', 'premium_breakdown',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_index(op.f('ix_document_risk_note_id'), table_name='document')
    op.drop_index(op.f('ix_document_policy_id'), table_name='document')
    op.drop_index(op.f('ix_document_entity_type'), table_name='document')
    op.drop_index(op.f('ix_document_client_id'), table_name='document')
    op.drop_index(op.f('ix_document_claim_id'), table_name='document')
    op.alter_column('document', 'doc_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('document', 'risk_note_id')
    op.drop_column('document', 'claim_id')
    op.drop_column('document', 'policy_id')
    op.drop_column('document', 'client_id')
    # ### end Alembic commands ###
