"""Add renewal statuses

Revision ID: 6f665a85343b
Revises: a6593c943069
Create Date: 2026-03-04 12:12:47.076581

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6f665a85343b'
down_revision = 'a6593c943069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Allow adding values to enums. These cannot be easily undone in downgrade.
    # We use 'COMMIT' because ADD VALUE cannot run in a transaction block in some PG versions.
    op.execute("ALTER TYPE policystatus ADD VALUE 'Renewal Invited'")
    op.execute("ALTER TYPE policystatus ADD VALUE 'Renewal Confirmed'")
    op.execute("ALTER TYPE risknotestatus ADD VALUE 'Renewal Invited'")
    op.execute("ALTER TYPE risknotestatus ADD VALUE 'Renewal Confirmed'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Enum values cannot be easily removed in PostgreSQL.
    # Manual system table manipulation or table recreation required if rollback is necessary.
    pass
    # ### end Alembic commands ###
