"""add_pricing_strategy_to_product

Revision ID: 78cb7d6ae496
Revises: 05af0e7b34cb
Create Date: 2026-02-18 15:43:59.007427

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '78cb7d6ae496'
down_revision = '05af0e7b34cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pricing_strategy_enum = sa.Enum('PERCENTAGE', 'FIXED_TIERED', 'MANUAL', name='pricingstrategy')
    pricing_strategy_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('product', sa.Column('pricing_strategy', pricing_strategy_enum, nullable=True))
    op.add_column('product', sa.Column('pricing_rules', sa.JSON(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE product SET pricing_strategy = 'PERCENTAGE' WHERE pricing_strategy IS NULL")
    op.execute("UPDATE product SET pricing_rules = '{}' WHERE pricing_rules IS NULL")
    
    # Now make them not null
    op.alter_column('product', 'pricing_strategy', nullable=False)
    op.alter_column('product', 'pricing_rules', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'pricing_rules')
    op.drop_column('product', 'pricing_strategy')
    sa.Enum(name='pricingstrategy').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
