"""Decimal migration and Soft Delete

Revision ID: 7c8fc97da876
Revises: 51f56db2b8a9
Create Date: 2026-02-13 10:55:03.691457

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7c8fc97da876'
down_revision = '51f56db2b8a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('claim', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('claim', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('claim', sa.Column('deleted_by_id', sa.Uuid(), nullable=True))
    op.alter_column('claim', 'reserve_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_claim_deleted_at'), 'claim', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'claim', 'user', ['deleted_by_id'], ['id'])
    op.add_column('client', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('client', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('client', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('client', sa.Column('deleted_by_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_client_deleted_at'), 'client', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'client', 'user', ['deleted_by_id'], ['id'])
    op.add_column('correspondence', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('correspondence', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('correspondence', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('correspondence', sa.Column('deleted_by_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_correspondence_deleted_at'), 'correspondence', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'correspondence', 'user', ['deleted_by_id'], ['id'])
    op.add_column('insurer', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('insurer', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('insurer', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('insurer', sa.Column('deleted_by_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_insurer_deleted_at'), 'insurer', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'insurer', 'user', ['deleted_by_id'], ['id'])
    op.add_column('invoice', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('invoice', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('invoice', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('invoice', sa.Column('deleted_by_id', sa.Uuid(), nullable=True))
    op.alter_column('invoice', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('invoice', 'balance_due',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_invoice_deleted_at'), 'invoice', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'invoice', 'user', ['deleted_by_id'], ['id'])
    op.alter_column('invoicelineitem', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.add_column('policy', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('policy', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('policy', sa.Column('deleted_by_id', sa.Uuid(), nullable=True))
    op.alter_column('policy', 'total_premium',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_policy_deleted_at'), 'policy', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'policy', 'user', ['deleted_by_id'], ['id'])
    op.add_column('product', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('product', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('product', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('product', sa.Column('deleted_by_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_product_deleted_at'), 'product', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'product', 'user', ['deleted_by_id'], ['id'])
    op.add_column('receipt', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('receipt', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('receipt', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('receipt', sa.Column('deleted_by_id', sa.Uuid(), nullable=True))
    op.alter_column('receipt', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('receipt', 'unallocated_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_receipt_deleted_at'), 'receipt', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'receipt', 'user', ['deleted_by_id'], ['id'])
    op.alter_column('receiptallocation', 'amount_allocated',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.add_column('risknote', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('risknote', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('risknote', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('risknote', sa.Column('deleted_by_id', sa.Uuid(), nullable=True))
    op.alter_column('risknote', 'risk_note_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('risknote', 'net_premium',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('risknote', 'commission_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('risknote', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_risknote_deleted_at'), 'risknote', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'risknote', 'user', ['deleted_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'risknote', type_='foreignkey')
    op.drop_index(op.f('ix_risknote_deleted_at'), table_name='risknote')
    op.alter_column('risknote', 'total_amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('risknote', 'commission_amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('risknote', 'net_premium',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('risknote', 'risk_note_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('risknote', 'deleted_by_id')
    op.drop_column('risknote', 'deleted_at')
    op.drop_column('risknote', 'updated_at')
    op.drop_column('risknote', 'created_at')
    op.alter_column('receiptallocation', 'amount_allocated',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_constraint(None, 'receipt', type_='foreignkey')
    op.drop_index(op.f('ix_receipt_deleted_at'), table_name='receipt')
    op.alter_column('receipt', 'unallocated_amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('receipt', 'amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('receipt', 'deleted_by_id')
    op.drop_column('receipt', 'deleted_at')
    op.drop_column('receipt', 'updated_at')
    op.drop_column('receipt', 'created_at')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_index(op.f('ix_product_deleted_at'), table_name='product')
    op.drop_column('product', 'deleted_by_id')
    op.drop_column('product', 'deleted_at')
    op.drop_column('product', 'updated_at')
    op.drop_column('product', 'created_at')
    op.drop_constraint(None, 'policy', type_='foreignkey')
    op.drop_index(op.f('ix_policy_deleted_at'), table_name='policy')
    op.alter_column('policy', 'total_premium',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('policy', 'deleted_by_id')
    op.drop_column('policy', 'deleted_at')
    op.drop_column('policy', 'updated_at')
    op.alter_column('invoicelineitem', 'amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.drop_index(op.f('ix_invoice_deleted_at'), table_name='invoice')
    op.alter_column('invoice', 'balance_due',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('invoice', 'total_amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('invoice', 'deleted_by_id')
    op.drop_column('invoice', 'deleted_at')
    op.drop_column('invoice', 'updated_at')
    op.drop_column('invoice', 'created_at')
    op.drop_constraint(None, 'insurer', type_='foreignkey')
    op.drop_index(op.f('ix_insurer_deleted_at'), table_name='insurer')
    op.drop_column('insurer', 'deleted_by_id')
    op.drop_column('insurer', 'deleted_at')
    op.drop_column('insurer', 'updated_at')
    op.drop_column('insurer', 'created_at')
    op.drop_constraint(None, 'correspondence', type_='foreignkey')
    op.drop_index(op.f('ix_correspondence_deleted_at'), table_name='correspondence')
    op.drop_column('correspondence', 'deleted_by_id')
    op.drop_column('correspondence', 'deleted_at')
    op.drop_column('correspondence', 'updated_at')
    op.drop_column('correspondence', 'created_at')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_index(op.f('ix_client_deleted_at'), table_name='client')
    op.drop_column('client', 'deleted_by_id')
    op.drop_column('client', 'deleted_at')
    op.drop_column('client', 'updated_at')
    op.drop_column('client', 'created_at')
    op.drop_constraint(None, 'claim', type_='foreignkey')
    op.drop_index(op.f('ix_claim_deleted_at'), table_name='claim')
    op.alter_column('claim', 'reserve_amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('claim', 'deleted_by_id')
    op.drop_column('claim', 'deleted_at')
    op.drop_column('claim', 'updated_at')
    op.drop_column('claim', 'created_at')
    # ### end Alembic commands ###
