"""Add insurance models

Revision ID: 835e5ddfd056
Revises: 1a31ce608336
Create Date: 2026-01-22 00:09:33.846879

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '835e5ddfd056'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('client_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kra_pin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('physical_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_person', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_kra_pin'), 'client', ['kra_pin'], unique=True)
    op.create_index(op.f('ix_client_name'), 'client', ['name'], unique=False)
    op.create_table('insurer',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurer_name'), 'insurer', ['name'], unique=True)
    op.create_table('payment',
    sa.Column('receipt_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_received', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number')
    )
    op.create_table('correspondence',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_logged', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('insurer_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('class_of_insurance', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_benefits', sa.JSON(), nullable=False),
    sa.Column('default_clauses', sa.JSON(), nullable=False),
    sa.Column('default_commission_rate', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['insurer_id'], ['insurer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy',
    sa.Column('policy_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_policy_number'), 'policy', ['policy_number'], unique=True)
    op.create_table('riskitem',
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sum_insured', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('benefits', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risknote',
    sa.Column('risk_note_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('basic_premium', sa.Float(), nullable=False),
    sa.Column('training_levy', sa.Float(), nullable=False),
    sa.Column('phcf_levy', sa.Float(), nullable=False),
    sa.Column('stamp_duty', sa.Float(), nullable=False),
    sa.Column('gross_premium', sa.Float(), nullable=False),
    sa.Column('commission_amount', sa.Float(), nullable=False),
    sa.Column('special_clauses', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_note_number')
    )
    op.create_table('claim',
    sa.Column('claim_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('risk_item_id', sa.Uuid(), nullable=True),
    sa.Column('date_of_loss', sa.Date(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reserve_amount', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.id'], ),
    sa.ForeignKeyConstraint(['risk_item_id'], ['riskitem.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_number')
    )
    op.create_table('paymentallocation',
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('risk_note_id', sa.Uuid(), nullable=False),
    sa.Column('amount_allocated', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['risk_note_id'], ['risknote.id'], ),
    sa.PrimaryKeyConstraint('payment_id', 'risk_note_id')
    )
    op.create_table('policydocument',
    sa.Column('document_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('policy_id', sa.Uuid(), nullable=True),
    sa.Column('risk_item_id', sa.Uuid(), nullable=True),
    sa.Column('risk_note_id', sa.Uuid(), nullable=True),
    sa.Column('claim_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.id'], ),
    sa.ForeignKeyConstraint(['risk_item_id'], ['riskitem.id'], ),
    sa.ForeignKeyConstraint(['risk_note_id'], ['risknote.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policydocument')
    op.drop_table('paymentallocation')
    op.drop_table('claim')
    op.drop_table('risknote')
    op.drop_table('riskitem')
    op.drop_index(op.f('ix_policy_policy_number'), table_name='policy')
    op.drop_table('policy')
    op.drop_table('product')
    op.drop_table('correspondence')
    op.drop_table('payment')
    op.drop_index(op.f('ix_insurer_name'), table_name='insurer')
    op.drop_table('insurer')
    op.drop_index(op.f('ix_client_name'), table_name='client')
    op.drop_index(op.f('ix_client_kra_pin'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
