"""add status to receipt

Revision ID: 86d3670a3ccf
Revises: 93cb54fa5fca
Create Date: 2026-01-29 12:24:22.451225

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '86d3670a3ccf'
down_revision = '93cb54fa5fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE receipt SET status = 'Active'")
    op.alter_column('receipt', 'status', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt', 'status')
    # ### end Alembic commands ###
