"""fix receipt allocation relationship

Revision ID: 93cb54fa5fca
Revises: 0774676eff5c
Create Date: 2026-01-28 11:42:52.362401

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '93cb54fa5fca'
down_revision = '0774676eff5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receiptallocation', sa.Column('risk_note_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'receiptallocation', 'risknote', ['risk_note_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receiptallocation', type_='foreignkey')
    op.drop_column('receiptallocation', 'risk_note_id')
    # ### end Alembic commands ###
