"""Add missing fields to Item and others

Revision ID: 96c0ac06ec9c
Revises: 7c8fc97da876
Create Date: 2026-02-13 11:18:13.085253

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '96c0ac06ec9c'
down_revision = '7c8fc97da876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('item', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('item', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('item', sa.Column('deleted_by_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_item_deleted_at'), 'item', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'item', 'user', ['deleted_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_index(op.f('ix_item_deleted_at'), table_name='item')
    op.drop_column('item', 'deleted_by_id')
    op.drop_column('item', 'deleted_at')
    op.drop_column('item', 'updated_at')
    op.drop_column('item', 'created_at')
    # ### end Alembic commands ###
