"""final refined architecture overhaul v2

Revision ID: ae3b5ec0bde2
Revises: 86d3670a3ccf
Create Date: 2026-01-29 13:37:56.764641

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ae3b5ec0bde2'
down_revision = '86d3670a3ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create Enum types manually for Postgres
    pricing_strategy = postgresql.ENUM('PERCENTAGE', 'FIXED_TIERED', 'MANUAL', name='pricingstrategy')
    pricing_strategy.create(op.get_bind())
    user_role = postgresql.ENUM('ADMIN', 'UNDERWRITER', 'CASHIER', 'VIEWER', name='userrole')
    user_role.create(op.get_bind())

    op.create_table('document',
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claimevent',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('policydocument')
    
    # 1. Add columns as nullable first
    op.add_column('claim', sa.Column('date_reported', sa.Date(), nullable=True))
    op.add_column('client', sa.Column('contacts', sa.JSON(), nullable=True))
    op.add_column('policy', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('product', sa.Column('pricing_strategy', sa.Enum('PERCENTAGE', 'FIXED_TIERED', 'MANUAL', name='pricingstrategy'), nullable=True))
    op.add_column('product', sa.Column('pricing_rules', sa.JSON(), nullable=True))
    op.add_column('product', sa.Column('form_schema', sa.JSON(), nullable=True))
    op.add_column('receipt', sa.Column('unallocated_amount', sa.Float(), nullable=True))
    op.add_column('riskitem', sa.Column('version_number', sa.Integer(), nullable=True))
    op.add_column('riskitem', sa.Column('valid_from', sa.Date(), nullable=True))
    op.add_column('riskitem', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('riskitem', sa.Column('cover_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('riskitem', sa.Column('total_premium', sa.Float(), nullable=True))
    op.add_column('riskitem', sa.Column('premium_breakdown', sa.JSON(), nullable=True))
    op.add_column('riskitem', sa.Column('risk_details', sa.JSON(), nullable=True))
    op.add_column('risknote', sa.Column('payment_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('risknote', sa.Column('net_premium', sa.Float(), nullable=True))
    op.add_column('risknote', sa.Column('taxes', sa.JSON(), nullable=True))
    op.add_column('risknote', sa.Column('total_amount', sa.Float(), nullable=True))
    op.add_column('risknote', sa.Column('items_snapshot', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('role', sa.Enum('ADMIN', 'UNDERWRITER', 'CASHIER', 'VIEWER', name='userrole'), nullable=True))

    # 2. Update existing rows with defaults
    op.execute("UPDATE claim SET date_reported = NOW()")
    op.execute("UPDATE client SET contacts = '[]'::json")
    op.execute("UPDATE policy SET created_at = NOW()")
    op.execute("UPDATE product SET pricing_strategy = 'PERCENTAGE', pricing_rules = '{}'::json, form_schema = '[]'::json")
    op.execute("UPDATE receipt SET unallocated_amount = amount")
    op.execute("UPDATE riskitem SET version_number = 1, valid_from = NOW(), is_active = true, cover_description = 'Standard', total_premium = 0, premium_breakdown = '{}'::json, risk_details = '{}'::json")
    op.execute("UPDATE risknote SET payment_status = 'Unpaid', net_premium = 0, taxes = '{}'::json, total_amount = 0, items_snapshot = '{}'::json")
    op.execute("UPDATE \"user\" SET role = 'VIEWER'")

    # 3. Set columns to NOT NULL
    op.alter_column('claim', 'date_reported', nullable=False)
    op.alter_column('client', 'contacts', nullable=False)
    op.alter_column('policy', 'created_at', nullable=False)
    op.alter_column('product', 'pricing_strategy', nullable=False)
    op.alter_column('product', 'pricing_rules', nullable=False)
    op.alter_column('product', 'form_schema', nullable=False)
    op.alter_column('receipt', 'unallocated_amount', nullable=False)
    op.alter_column('riskitem', 'version_number', nullable=False)
    op.alter_column('riskitem', 'valid_from', nullable=False)
    op.alter_column('riskitem', 'is_active', nullable=False)
    op.alter_column('riskitem', 'cover_description', nullable=False)
    op.alter_column('riskitem', 'total_premium', nullable=False)
    op.alter_column('riskitem', 'premium_breakdown', nullable=False)
    op.alter_column('riskitem', 'risk_details', nullable=False)
    op.alter_column('risknote', 'payment_status', nullable=False)
    op.alter_column('risknote', 'net_premium', nullable=False)
    op.alter_column('risknote', 'taxes', nullable=False)
    op.alter_column('risknote', 'total_amount', nullable=False)
    op.alter_column('risknote', 'items_snapshot', nullable=False)
    op.alter_column('user', 'role', nullable=False)

    # 4. Remaining changes
    op.drop_column('client', 'contact_person')
    op.add_column('receipt', sa.Column('created_by_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'receipt', 'user', ['created_by_id'], ['id'])
    op.add_column('riskitem', sa.Column('valid_to', sa.Date(), nullable=True))
    op.drop_column('riskitem', 'benefits')
    op.drop_column('riskitem', 'sum_insured')
    op.drop_column('riskitem', 'details')
    op.drop_column('riskitem', 'identifier')
    op.add_column('risknote', sa.Column('previous_risk_note_id', sa.Uuid(), nullable=True))
    op.add_column('risknote', sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('risknote', sa.Column('created_by_id', sa.Uuid(), nullable=True))
    op.drop_constraint('risknote_risk_note_number_key', 'risknote', type_='unique')
    op.create_foreign_key(None, 'risknote', 'user', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'risknote', 'risknote', ['previous_risk_note_id'], ['id'])
    op.drop_column('risknote', 'premium_breakdown')
    op.drop_column('risknote', 'risk_item_snapshot')
    op.drop_column('risknote', 'risk_note_number')
    op.drop_column('risknote', 'benefits_snapshot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.add_column('risknote', sa.Column('benefits_snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('risknote', sa.Column('risk_note_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('risknote', sa.Column('risk_item_snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('risknote', sa.Column('premium_breakdown', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'risknote', type_='foreignkey')
    op.drop_constraint(None, 'risknote', type_='foreignkey')
    op.create_unique_constraint(op.f('risknote_risk_note_number_key'), 'risknote', ['risk_note_number'])
    op.drop_column('risknote', 'items_snapshot')
    op.drop_column('risknote', 'total_amount')
    op.drop_column('risknote', 'taxes')
    op.drop_column('risknote', 'net_premium')
    op.drop_column('risknote', 'payment_status')
    op.drop_column('risknote', 'created_by_id')
    op.drop_column('risknote', 'invoice_number')
    op.drop_column('risknote', 'previous_risk_note_id')
    op.add_column('riskitem', sa.Column('identifier', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('riskitem', sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('riskitem', sa.Column('sum_insured', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('riskitem', sa.Column('benefits', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('riskitem', 'risk_details')
    op.drop_column('riskitem', 'premium_breakdown')
    op.drop_column('riskitem', 'total_premium')
    op.drop_column('riskitem', 'cover_description')
    op.drop_column('riskitem', 'is_active')
    op.drop_column('riskitem', 'valid_to')
    op.drop_column('riskitem', 'valid_from')
    op.drop_column('riskitem', 'version_number')
    op.drop_constraint(None, 'receipt', type_='foreignkey')
    op.drop_column('receipt', 'created_by_id')
    op.drop_column('receipt', 'unallocated_amount')
    op.drop_column('product', 'form_schema')
    op.drop_column('product', 'pricing_rules')
    op.drop_column('product', 'pricing_strategy')
    op.drop_column('policy', 'created_at')
    op.add_column('client', sa.Column('contact_person', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('client', 'contacts')
    op.drop_column('claim', 'date_reported')
    op.create_table('policydocument',
    sa.Column('document_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('policy_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('risk_item_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('risk_note_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('claim_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], name=op.f('policydocument_claim_id_fkey')),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.id'], name=op.f('policydocument_policy_id_fkey')),
    sa.ForeignKeyConstraint(['risk_item_id'], ['riskitem.id'], name=op.f('policydocument_risk_item_id_fkey')),
    sa.ForeignKeyConstraint(['risk_note_id'], ['risknote.id'], name=op.f('policydocument_risk_note_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('policydocument_pkey'))
    )
    op.drop_table('claimevent')
    op.drop_table('document')
    # ### end Alembic commands ###
