"""sync models

Revision ID: b1fcc5550935
Revises: 835e5ddfd056
Create Date: 2026-01-23 08:13:01.259818

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b1fcc5550935'
down_revision = '835e5ddfd056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('postal_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('client', 'physical_address')
    op.add_column('risknote', sa.Column('premium_breakdown', sa.JSON(), nullable=False))
    op.add_column('risknote', sa.Column('benefits_snapshot', sa.JSON(), nullable=False))
    op.add_column('risknote', sa.Column('risk_item_snapshot', sa.JSON(), nullable=False))
    op.drop_column('risknote', 'phcf_levy')
    op.drop_column('risknote', 'stamp_duty')
    op.drop_column('risknote', 'gross_premium')
    op.drop_column('risknote', 'basic_premium')
    op.drop_column('risknote', 'training_levy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risknote', sa.Column('training_levy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('risknote', sa.Column('basic_premium', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('risknote', sa.Column('gross_premium', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('risknote', sa.Column('stamp_duty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('risknote', sa.Column('phcf_levy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('risknote', 'risk_item_snapshot')
    op.drop_column('risknote', 'benefits_snapshot')
    op.drop_column('risknote', 'premium_breakdown')
    op.add_column('client', sa.Column('physical_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('client', 'postal_address')
    # ### end Alembic commands ###
