"""Replace status strings with Enums

Revision ID: c9be6269c828
Revises: 96c0ac06ec9c
Create Date: 2026-02-13 11:31:58.264460

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c9be6269c828'
down_revision = '96c0ac06ec9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claim', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('REPORTED', 'ASSESSED', 'PAID', 'REJECTED', 'CLOSED', name='claimstatus'),
               existing_nullable=False,
               postgresql_using="status::claimstatus")
    op.alter_column('claimevent', 'event_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('NOTIFICATION', 'ASSESSMENT', 'CORRESPONDENCE', 'PAYMENT', name='claimeventtype'),
               existing_nullable=False,
               postgresql_using="event_type::claimeventtype")
    op.alter_column('document', 'entity_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('CLIENT', 'POLICY', 'CLAIM', 'USER', 'RISK_NOTE', name='documententitytype'),
               existing_nullable=False,
               postgresql_using="entity_type::documententitytype")
    op.alter_column('document', 'document_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('LOGBOOK', 'ID', 'VALUATION', 'POLICE_ABSTRACT', 'RECEIPT', 'OTHER', name='documenttype'),
               existing_nullable=False,
               postgresql_using="document_type::documenttype")
    op.alter_column('invoice', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('UNPAID', 'PARTIAL', 'PAID', 'CANCELLED', name='invoicestatus'),
               existing_nullable=False,
               postgresql_using="status::invoicestatus")
    op.alter_column('policy', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ACTIVE', 'EXPIRED', 'CANCELLED', 'LAPSED', name='policystatus'),
               existing_nullable=False,
               postgresql_using="status::policystatus")
    op.alter_column('receipt', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ACTIVE', 'VOIDED', name='receiptstatus'),
               existing_nullable=False,
               postgresql_using="status::receiptstatus")
    op.alter_column('risknote', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('DRAFT', 'ACTIVE', 'CANCELLED', name='risknotestatus'),
               existing_nullable=False,
               postgresql_using="status::risknotestatus")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('risknote', 'status',
               existing_type=sa.Enum('DRAFT', 'ACTIVE', 'CANCELLED', name='risknotestatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('receipt', 'status',
               existing_type=sa.Enum('ACTIVE', 'VOIDED', name='receiptstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('policy', 'status',
               existing_type=sa.Enum('ACTIVE', 'EXPIRED', 'CANCELLED', 'LAPSED', name='policystatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('invoice', 'status',
               existing_type=sa.Enum('UNPAID', 'PARTIAL', 'PAID', 'CANCELLED', name='invoicestatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('document', 'document_type',
               existing_type=sa.Enum('LOGBOOK', 'ID', 'VALUATION', 'POLICE_ABSTRACT', 'RECEIPT', 'OTHER', name='documenttype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('document', 'entity_type',
               existing_type=sa.Enum('CLIENT', 'POLICY', 'CLAIM', 'USER', 'RISK_NOTE', name='documententitytype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('claimevent', 'event_type',
               existing_type=sa.Enum('NOTIFICATION', 'ASSESSMENT', 'CORRESPONDENCE', 'PAYMENT', name='claimeventtype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('claim', 'status',
               existing_type=sa.Enum('REPORTED', 'ASSESSED', 'PAID', 'REJECTED', 'CLOSED', name='claimstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
