"""add doc_metadata to document model

Revision ID: d2009cd3d8cc
Revises: ae3b5ec0bde2
Create Date: 2026-01-30 10:59:28.306030

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd2009cd3d8cc'
down_revision = 'ae3b5ec0bde2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('doc_metadata', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'doc_metadata')
    # ### end Alembic commands ###
