"""sync_models_with_transactional_pattern

Revision ID: e3ccbd29a18e
Revises: 540358348e97
Create Date: 2026-02-16 11:07:39.572525

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e3ccbd29a18e'
down_revision = '540358348e97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('claim_claim_number_key'), 'claim', type_='unique')
    op.create_index(op.f('ix_claim_claim_number'), 'claim', ['claim_number'], unique=True)
    op.drop_index(op.f('ix_document_claim_id'), table_name='document')
    op.drop_index(op.f('ix_document_client_id'), table_name='document')
    op.drop_index(op.f('ix_document_entity_id'), table_name='document')
    op.drop_index(op.f('ix_document_entity_type'), table_name='document')
    op.drop_index(op.f('ix_document_policy_id'), table_name='document')
    op.drop_index(op.f('ix_document_risk_note_id'), table_name='document')
    op.drop_constraint(op.f('document_claim_id_fkey'), 'document', type_='foreignkey')
    op.drop_constraint(op.f('document_risk_note_id_fkey'), 'document', type_='foreignkey')
    op.drop_constraint(op.f('document_policy_id_fkey'), 'document', type_='foreignkey')
    op.drop_constraint(op.f('document_client_id_fkey'), 'document', type_='foreignkey')
    op.drop_column('document', 'client_id')
    op.drop_column('document', 'claim_id')
    op.drop_column('document', 'policy_id')
    op.drop_column('document', 'risk_note_id')
    # Create the transactiontype Enum type before using it in alter_column
    sa.Enum('NEW_BUSINESS', 'RENEWAL', 'ENDORSEMENT', 'CANCELLATION', name='transactiontype').create(op.get_bind(), checkfirst=True)
    op.alter_column('risknote', 'transaction_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('NEW_BUSINESS', 'RENEWAL', 'ENDORSEMENT', 'CANCELLATION', name='transactiontype'),
               existing_nullable=False,
               postgresql_using="transaction_type::transactiontype")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('risknote', 'transaction_type',
               existing_type=sa.Enum('NEW_BUSINESS', 'RENEWAL', 'ENDORSEMENT', 'CANCELLATION', name='transactiontype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('document', sa.Column('risk_note_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('policy_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('claim_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('document_client_id_fkey'), 'document', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('document_policy_id_fkey'), 'document', 'policy', ['policy_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('document_risk_note_id_fkey'), 'document', 'risknote', ['risk_note_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('document_claim_id_fkey'), 'document', 'claim', ['claim_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_document_risk_note_id'), 'document', ['risk_note_id'], unique=False)
    op.create_index(op.f('ix_document_policy_id'), 'document', ['policy_id'], unique=False)
    op.create_index(op.f('ix_document_entity_type'), 'document', ['entity_type'], unique=False)
    op.create_index(op.f('ix_document_entity_id'), 'document', ['entity_id'], unique=False)
    op.create_index(op.f('ix_document_client_id'), 'document', ['client_id'], unique=False)
    op.create_index(op.f('ix_document_claim_id'), 'document', ['claim_id'], unique=False)
    op.drop_index(op.f('ix_claim_claim_number'), table_name='claim')
    op.create_unique_constraint(op.f('claim_claim_number_key'), 'claim', ['claim_number'])
    # ### end Alembic commands ###
