"""add missing product columns

Revision ID: e765bc387434
Revises: 6f665a85343b
Create Date: 2026-04-28 08:34:26.903133

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e765bc387434'
down_revision = '6f665a85343b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claim', 'reserve_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.create_index('ix_claim_policy_status', 'claim', ['policy_id', 'status'], unique=False)
    op.create_index(op.f('ix_claim_status'), 'claim', ['status'], unique=False)
    op.create_index(op.f('ix_client_client_type'), 'client', ['client_type'], unique=False)
    op.alter_column('invoice', 'total_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('invoice', 'balance_due',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.create_index('ix_invoice_client_date', 'invoice', ['client_id', 'date_issued'], unique=False)
    op.create_index('ix_invoice_client_status', 'invoice', ['client_id', 'status'], unique=False)
    op.create_index(op.f('ix_invoice_status'), 'invoice', ['status'], unique=False)
    op.alter_column('invoicelineitem', 'amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.create_index('ix_policy_client_status', 'policy', ['client_id', 'status'], unique=False)
    op.create_index(op.f('ix_policy_status'), 'policy', ['status'], unique=False)
    op.drop_column('policy', 'end_date')
    op.drop_column('policy', 'description')
    op.drop_column('policy', 'start_date')
    op.drop_column('policy', 'total_premium')
    op.drop_column('policy', 'premium_breakdown')
    op.add_column('product', sa.Column('default_benefits_and_limits', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('product', sa.Column('default_excesses', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('product', sa.Column('default_special_clauses', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('receipt', 'amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('receipt', 'unallocated_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.create_index(op.f('ix_receipt_status'), 'receipt', ['status'], unique=False)
    op.alter_column('receiptallocation', 'amount_allocated',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.add_column('risknote', sa.Column('effective_date', sa.Date(), nullable=False))
    op.add_column('risknote', sa.Column('coverage_start', sa.Date(), nullable=False))
    op.add_column('risknote', sa.Column('coverage_end', sa.Date(), nullable=False))
    op.alter_column('risknote', 'net_premium',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('risknote', 'commission_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('risknote', 'total_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('risknote', 'cover_snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.create_index(op.f('ix_risknote_effective_date'), 'risknote', ['effective_date'], unique=False)
    op.create_index('ix_risknote_policy_created', 'risknote', ['policy_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_risknote_status'), 'risknote', ['status'], unique=False)
    op.create_index(op.f('ix_risknote_transaction_type'), 'risknote', ['transaction_type'], unique=False)
    op.drop_column('risknote', 'end_date')
    op.drop_column('risknote', 'start_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risknote', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('risknote', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_risknote_transaction_type'), table_name='risknote')
    op.drop_index(op.f('ix_risknote_status'), table_name='risknote')
    op.drop_index('ix_risknote_policy_created', table_name='risknote')
    op.drop_index(op.f('ix_risknote_effective_date'), table_name='risknote')
    op.alter_column('risknote', 'cover_snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('risknote', 'total_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('risknote', 'commission_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('risknote', 'net_premium',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.drop_column('risknote', 'coverage_end')
    op.drop_column('risknote', 'coverage_start')
    op.drop_column('risknote', 'effective_date')
    op.alter_column('receiptallocation', 'amount_allocated',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.drop_index(op.f('ix_receipt_status'), table_name='receipt')
    op.alter_column('receipt', 'unallocated_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('receipt', 'amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.drop_column('product', 'default_special_clauses')
    op.drop_column('product', 'default_excesses')
    op.drop_column('product', 'default_benefits_and_limits')
    op.add_column('policy', sa.Column('premium_breakdown', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('policy', sa.Column('total_premium', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('policy', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('policy', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('policy', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_policy_status'), table_name='policy')
    op.drop_index('ix_policy_client_status', table_name='policy')
    op.alter_column('invoicelineitem', 'amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.drop_index(op.f('ix_invoice_status'), table_name='invoice')
    op.drop_index('ix_invoice_client_status', table_name='invoice')
    op.drop_index('ix_invoice_client_date', table_name='invoice')
    op.alter_column('invoice', 'balance_due',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('invoice', 'total_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.drop_index(op.f('ix_client_client_type'), table_name='client')
    op.drop_index(op.f('ix_claim_status'), table_name='claim')
    op.drop_index('ix_claim_policy_status', table_name='claim')
    op.alter_column('claim', 'reserve_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    # ### end Alembic commands ###
