"""Refine client address fields

Revision ID: ed0f67e684f7
Revises: 300464e5e502
Create Date: 2026-02-09 06:53:09.802394

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ed0f67e684f7'
down_revision = '300464e5e502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('client', sa.Column('town', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'town')
    op.drop_column('client', 'postal_code')
    # ### end Alembic commands ###
