/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutCatalogRouteImport } from './routes/_layout/catalog'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutRenewalsIndexRouteImport } from './routes/_layout/renewals.index'
import { Route as LayoutClientsIndexRouteImport } from './routes/_layout/clients.index'
import { Route as LayoutCatalogIndexRouteImport } from './routes/_layout/catalog.index'
import { Route as PrintRiskNotesIdRouteImport } from './routes/print/risk-notes.$id'
import { Route as LayoutClientsClientIdRouteImport } from './routes/_layout/clients.$clientId'
import { Route as LayoutClientsClientIdIndexRouteImport } from './routes/_layout/clients.$clientId.index'
import { Route as LayoutCatalogProductsIndexRouteImport } from './routes/_layout/catalog.products.index'
import { Route as LayoutCatalogInsurersIndexRouteImport } from './routes/_layout/catalog.insurers.index'
import { Route as LayoutClientsClientIdSettingsRouteImport } from './routes/_layout/clients.$clientId.settings'
import { Route as LayoutClientsClientIdOverviewRouteImport } from './routes/_layout/clients.$clientId.overview'
import { Route as LayoutClientsClientIdInvoicesRouteImport } from './routes/_layout/clients.$clientId.invoices'
import { Route as LayoutClientsClientIdDocumentsRouteImport } from './routes/_layout/clients.$clientId.documents'
import { Route as LayoutCatalogProductsProductIdRouteImport } from './routes/_layout/catalog.products.$productId'
import { Route as LayoutCatalogInsurersInsurerIdRouteImport } from './routes/_layout/catalog.insurers.$insurerId'
import { Route as LayoutClientsClientIdPoliciesIndexRouteImport } from './routes/_layout/clients.$clientId.policies.index'
import { Route as LayoutClientsClientIdPoliciesPolicyIdRouteImport } from './routes/_layout/clients.$clientId.policies.$policyId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCatalogRoute = LayoutCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRenewalsIndexRoute = LayoutRenewalsIndexRouteImport.update({
  id: '/renewals/',
  path: '/renewals/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutClientsIndexRoute = LayoutClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCatalogIndexRoute = LayoutCatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutCatalogRoute,
} as any)
const PrintRiskNotesIdRoute = PrintRiskNotesIdRouteImport.update({
  id: '/print/risk-notes/$id',
  path: '/print/risk-notes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutClientsClientIdRoute = LayoutClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutClientsClientIdIndexRoute =
  LayoutClientsClientIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutClientsClientIdRoute,
  } as any)
const LayoutCatalogProductsIndexRoute =
  LayoutCatalogProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => LayoutCatalogRoute,
  } as any)
const LayoutCatalogInsurersIndexRoute =
  LayoutCatalogInsurersIndexRouteImport.update({
    id: '/insurers/',
    path: '/insurers/',
    getParentRoute: () => LayoutCatalogRoute,
  } as any)
const LayoutClientsClientIdSettingsRoute =
  LayoutClientsClientIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutClientsClientIdRoute,
  } as any)
const LayoutClientsClientIdOverviewRoute =
  LayoutClientsClientIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => LayoutClientsClientIdRoute,
  } as any)
const LayoutClientsClientIdInvoicesRoute =
  LayoutClientsClientIdInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => LayoutClientsClientIdRoute,
  } as any)
const LayoutClientsClientIdDocumentsRoute =
  LayoutClientsClientIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => LayoutClientsClientIdRoute,
  } as any)
const LayoutCatalogProductsProductIdRoute =
  LayoutCatalogProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => LayoutCatalogRoute,
  } as any)
const LayoutCatalogInsurersInsurerIdRoute =
  LayoutCatalogInsurersInsurerIdRouteImport.update({
    id: '/insurers/$insurerId',
    path: '/insurers/$insurerId',
    getParentRoute: () => LayoutCatalogRoute,
  } as any)
const LayoutClientsClientIdPoliciesIndexRoute =
  LayoutClientsClientIdPoliciesIndexRouteImport.update({
    id: '/policies/',
    path: '/policies/',
    getParentRoute: () => LayoutClientsClientIdRoute,
  } as any)
const LayoutClientsClientIdPoliciesPolicyIdRoute =
  LayoutClientsClientIdPoliciesPolicyIdRouteImport.update({
    id: '/policies/$policyId',
    path: '/policies/$policyId',
    getParentRoute: () => LayoutClientsClientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/catalog': typeof LayoutCatalogRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/clients/$clientId': typeof LayoutClientsClientIdRouteWithChildren
  '/print/risk-notes/$id': typeof PrintRiskNotesIdRoute
  '/catalog/': typeof LayoutCatalogIndexRoute
  '/clients': typeof LayoutClientsIndexRoute
  '/renewals': typeof LayoutRenewalsIndexRoute
  '/catalog/insurers/$insurerId': typeof LayoutCatalogInsurersInsurerIdRoute
  '/catalog/products/$productId': typeof LayoutCatalogProductsProductIdRoute
  '/clients/$clientId/documents': typeof LayoutClientsClientIdDocumentsRoute
  '/clients/$clientId/invoices': typeof LayoutClientsClientIdInvoicesRoute
  '/clients/$clientId/overview': typeof LayoutClientsClientIdOverviewRoute
  '/clients/$clientId/settings': typeof LayoutClientsClientIdSettingsRoute
  '/catalog/insurers': typeof LayoutCatalogInsurersIndexRoute
  '/catalog/products': typeof LayoutCatalogProductsIndexRoute
  '/clients/$clientId/': typeof LayoutClientsClientIdIndexRoute
  '/clients/$clientId/policies/$policyId': typeof LayoutClientsClientIdPoliciesPolicyIdRoute
  '/clients/$clientId/policies': typeof LayoutClientsClientIdPoliciesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/print/risk-notes/$id': typeof PrintRiskNotesIdRoute
  '/catalog': typeof LayoutCatalogIndexRoute
  '/clients': typeof LayoutClientsIndexRoute
  '/renewals': typeof LayoutRenewalsIndexRoute
  '/catalog/insurers/$insurerId': typeof LayoutCatalogInsurersInsurerIdRoute
  '/catalog/products/$productId': typeof LayoutCatalogProductsProductIdRoute
  '/clients/$clientId/documents': typeof LayoutClientsClientIdDocumentsRoute
  '/clients/$clientId/invoices': typeof LayoutClientsClientIdInvoicesRoute
  '/clients/$clientId/overview': typeof LayoutClientsClientIdOverviewRoute
  '/clients/$clientId/settings': typeof LayoutClientsClientIdSettingsRoute
  '/catalog/insurers': typeof LayoutCatalogInsurersIndexRoute
  '/catalog/products': typeof LayoutCatalogProductsIndexRoute
  '/clients/$clientId': typeof LayoutClientsClientIdIndexRoute
  '/clients/$clientId/policies/$policyId': typeof LayoutClientsClientIdPoliciesPolicyIdRoute
  '/clients/$clientId/policies': typeof LayoutClientsClientIdPoliciesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/catalog': typeof LayoutCatalogRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/clients/$clientId': typeof LayoutClientsClientIdRouteWithChildren
  '/print/risk-notes/$id': typeof PrintRiskNotesIdRoute
  '/_layout/catalog/': typeof LayoutCatalogIndexRoute
  '/_layout/clients/': typeof LayoutClientsIndexRoute
  '/_layout/renewals/': typeof LayoutRenewalsIndexRoute
  '/_layout/catalog/insurers/$insurerId': typeof LayoutCatalogInsurersInsurerIdRoute
  '/_layout/catalog/products/$productId': typeof LayoutCatalogProductsProductIdRoute
  '/_layout/clients/$clientId/documents': typeof LayoutClientsClientIdDocumentsRoute
  '/_layout/clients/$clientId/invoices': typeof LayoutClientsClientIdInvoicesRoute
  '/_layout/clients/$clientId/overview': typeof LayoutClientsClientIdOverviewRoute
  '/_layout/clients/$clientId/settings': typeof LayoutClientsClientIdSettingsRoute
  '/_layout/catalog/insurers/': typeof LayoutCatalogInsurersIndexRoute
  '/_layout/catalog/products/': typeof LayoutCatalogProductsIndexRoute
  '/_layout/clients/$clientId/': typeof LayoutClientsClientIdIndexRoute
  '/_layout/clients/$clientId/policies/$policyId': typeof LayoutClientsClientIdPoliciesPolicyIdRoute
  '/_layout/clients/$clientId/policies/': typeof LayoutClientsClientIdPoliciesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/catalog'
    | '/settings'
    | '/'
    | '/clients/$clientId'
    | '/print/risk-notes/$id'
    | '/catalog/'
    | '/clients'
    | '/renewals'
    | '/catalog/insurers/$insurerId'
    | '/catalog/products/$productId'
    | '/clients/$clientId/documents'
    | '/clients/$clientId/invoices'
    | '/clients/$clientId/overview'
    | '/clients/$clientId/settings'
    | '/catalog/insurers'
    | '/catalog/products'
    | '/clients/$clientId/'
    | '/clients/$clientId/policies/$policyId'
    | '/clients/$clientId/policies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/settings'
    | '/'
    | '/print/risk-notes/$id'
    | '/catalog'
    | '/clients'
    | '/renewals'
    | '/catalog/insurers/$insurerId'
    | '/catalog/products/$productId'
    | '/clients/$clientId/documents'
    | '/clients/$clientId/invoices'
    | '/clients/$clientId/overview'
    | '/clients/$clientId/settings'
    | '/catalog/insurers'
    | '/catalog/products'
    | '/clients/$clientId'
    | '/clients/$clientId/policies/$policyId'
    | '/clients/$clientId/policies'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/catalog'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/clients/$clientId'
    | '/print/risk-notes/$id'
    | '/_layout/catalog/'
    | '/_layout/clients/'
    | '/_layout/renewals/'
    | '/_layout/catalog/insurers/$insurerId'
    | '/_layout/catalog/products/$productId'
    | '/_layout/clients/$clientId/documents'
    | '/_layout/clients/$clientId/invoices'
    | '/_layout/clients/$clientId/overview'
    | '/_layout/clients/$clientId/settings'
    | '/_layout/catalog/insurers/'
    | '/_layout/catalog/products/'
    | '/_layout/clients/$clientId/'
    | '/_layout/clients/$clientId/policies/$policyId'
    | '/_layout/clients/$clientId/policies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  PrintRiskNotesIdRoute: typeof PrintRiskNotesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/catalog': {
      id: '/_layout/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof LayoutCatalogRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/renewals/': {
      id: '/_layout/renewals/'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof LayoutRenewalsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/clients/': {
      id: '/_layout/clients/'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof LayoutClientsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/catalog/': {
      id: '/_layout/catalog/'
      path: '/'
      fullPath: '/catalog/'
      preLoaderRoute: typeof LayoutCatalogIndexRouteImport
      parentRoute: typeof LayoutCatalogRoute
    }
    '/print/risk-notes/$id': {
      id: '/print/risk-notes/$id'
      path: '/print/risk-notes/$id'
      fullPath: '/print/risk-notes/$id'
      preLoaderRoute: typeof PrintRiskNotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/clients/$clientId': {
      id: '/_layout/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof LayoutClientsClientIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/clients/$clientId/': {
      id: '/_layout/clients/$clientId/'
      path: '/'
      fullPath: '/clients/$clientId/'
      preLoaderRoute: typeof LayoutClientsClientIdIndexRouteImport
      parentRoute: typeof LayoutClientsClientIdRoute
    }
    '/_layout/catalog/products/': {
      id: '/_layout/catalog/products/'
      path: '/products'
      fullPath: '/catalog/products'
      preLoaderRoute: typeof LayoutCatalogProductsIndexRouteImport
      parentRoute: typeof LayoutCatalogRoute
    }
    '/_layout/catalog/insurers/': {
      id: '/_layout/catalog/insurers/'
      path: '/insurers'
      fullPath: '/catalog/insurers'
      preLoaderRoute: typeof LayoutCatalogInsurersIndexRouteImport
      parentRoute: typeof LayoutCatalogRoute
    }
    '/_layout/clients/$clientId/settings': {
      id: '/_layout/clients/$clientId/settings'
      path: '/settings'
      fullPath: '/clients/$clientId/settings'
      preLoaderRoute: typeof LayoutClientsClientIdSettingsRouteImport
      parentRoute: typeof LayoutClientsClientIdRoute
    }
    '/_layout/clients/$clientId/overview': {
      id: '/_layout/clients/$clientId/overview'
      path: '/overview'
      fullPath: '/clients/$clientId/overview'
      preLoaderRoute: typeof LayoutClientsClientIdOverviewRouteImport
      parentRoute: typeof LayoutClientsClientIdRoute
    }
    '/_layout/clients/$clientId/invoices': {
      id: '/_layout/clients/$clientId/invoices'
      path: '/invoices'
      fullPath: '/clients/$clientId/invoices'
      preLoaderRoute: typeof LayoutClientsClientIdInvoicesRouteImport
      parentRoute: typeof LayoutClientsClientIdRoute
    }
    '/_layout/clients/$clientId/documents': {
      id: '/_layout/clients/$clientId/documents'
      path: '/documents'
      fullPath: '/clients/$clientId/documents'
      preLoaderRoute: typeof LayoutClientsClientIdDocumentsRouteImport
      parentRoute: typeof LayoutClientsClientIdRoute
    }
    '/_layout/catalog/products/$productId': {
      id: '/_layout/catalog/products/$productId'
      path: '/products/$productId'
      fullPath: '/catalog/products/$productId'
      preLoaderRoute: typeof LayoutCatalogProductsProductIdRouteImport
      parentRoute: typeof LayoutCatalogRoute
    }
    '/_layout/catalog/insurers/$insurerId': {
      id: '/_layout/catalog/insurers/$insurerId'
      path: '/insurers/$insurerId'
      fullPath: '/catalog/insurers/$insurerId'
      preLoaderRoute: typeof LayoutCatalogInsurersInsurerIdRouteImport
      parentRoute: typeof LayoutCatalogRoute
    }
    '/_layout/clients/$clientId/policies/': {
      id: '/_layout/clients/$clientId/policies/'
      path: '/policies'
      fullPath: '/clients/$clientId/policies'
      preLoaderRoute: typeof LayoutClientsClientIdPoliciesIndexRouteImport
      parentRoute: typeof LayoutClientsClientIdRoute
    }
    '/_layout/clients/$clientId/policies/$policyId': {
      id: '/_layout/clients/$clientId/policies/$policyId'
      path: '/policies/$policyId'
      fullPath: '/clients/$clientId/policies/$policyId'
      preLoaderRoute: typeof LayoutClientsClientIdPoliciesPolicyIdRouteImport
      parentRoute: typeof LayoutClientsClientIdRoute
    }
  }
}

interface LayoutCatalogRouteChildren {
  LayoutCatalogIndexRoute: typeof LayoutCatalogIndexRoute
  LayoutCatalogInsurersInsurerIdRoute: typeof LayoutCatalogInsurersInsurerIdRoute
  LayoutCatalogProductsProductIdRoute: typeof LayoutCatalogProductsProductIdRoute
  LayoutCatalogInsurersIndexRoute: typeof LayoutCatalogInsurersIndexRoute
  LayoutCatalogProductsIndexRoute: typeof LayoutCatalogProductsIndexRoute
}

const LayoutCatalogRouteChildren: LayoutCatalogRouteChildren = {
  LayoutCatalogIndexRoute: LayoutCatalogIndexRoute,
  LayoutCatalogInsurersInsurerIdRoute: LayoutCatalogInsurersInsurerIdRoute,
  LayoutCatalogProductsProductIdRoute: LayoutCatalogProductsProductIdRoute,
  LayoutCatalogInsurersIndexRoute: LayoutCatalogInsurersIndexRoute,
  LayoutCatalogProductsIndexRoute: LayoutCatalogProductsIndexRoute,
}

const LayoutCatalogRouteWithChildren = LayoutCatalogRoute._addFileChildren(
  LayoutCatalogRouteChildren,
)

interface LayoutClientsClientIdRouteChildren {
  LayoutClientsClientIdDocumentsRoute: typeof LayoutClientsClientIdDocumentsRoute
  LayoutClientsClientIdInvoicesRoute: typeof LayoutClientsClientIdInvoicesRoute
  LayoutClientsClientIdOverviewRoute: typeof LayoutClientsClientIdOverviewRoute
  LayoutClientsClientIdSettingsRoute: typeof LayoutClientsClientIdSettingsRoute
  LayoutClientsClientIdIndexRoute: typeof LayoutClientsClientIdIndexRoute
  LayoutClientsClientIdPoliciesPolicyIdRoute: typeof LayoutClientsClientIdPoliciesPolicyIdRoute
  LayoutClientsClientIdPoliciesIndexRoute: typeof LayoutClientsClientIdPoliciesIndexRoute
}

const LayoutClientsClientIdRouteChildren: LayoutClientsClientIdRouteChildren = {
  LayoutClientsClientIdDocumentsRoute: LayoutClientsClientIdDocumentsRoute,
  LayoutClientsClientIdInvoicesRoute: LayoutClientsClientIdInvoicesRoute,
  LayoutClientsClientIdOverviewRoute: LayoutClientsClientIdOverviewRoute,
  LayoutClientsClientIdSettingsRoute: LayoutClientsClientIdSettingsRoute,
  LayoutClientsClientIdIndexRoute: LayoutClientsClientIdIndexRoute,
  LayoutClientsClientIdPoliciesPolicyIdRoute:
    LayoutClientsClientIdPoliciesPolicyIdRoute,
  LayoutClientsClientIdPoliciesIndexRoute:
    LayoutClientsClientIdPoliciesIndexRoute,
}

const LayoutClientsClientIdRouteWithChildren =
  LayoutClientsClientIdRoute._addFileChildren(
    LayoutClientsClientIdRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutCatalogRoute: typeof LayoutCatalogRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutClientsClientIdRoute: typeof LayoutClientsClientIdRouteWithChildren
  LayoutClientsIndexRoute: typeof LayoutClientsIndexRoute
  LayoutRenewalsIndexRoute: typeof LayoutRenewalsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutCatalogRoute: LayoutCatalogRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutClientsClientIdRoute: LayoutClientsClientIdRouteWithChildren,
  LayoutClientsIndexRoute: LayoutClientsIndexRoute,
  LayoutRenewalsIndexRoute: LayoutRenewalsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  PrintRiskNotesIdRoute: PrintRiskNotesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
