/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutClientsIndexRouteImport } from './routes/_layout/clients.index'
import { Route as PrintRiskNotesIdRouteImport } from './routes/print/risk-notes.$id'
import { Route as LayoutPoliciesPolicyIdRouteImport } from './routes/_layout/policies.$policyId'
import { Route as LayoutClientsClientIdRouteImport } from './routes/_layout/clients.$clientId'
import { Route as LayoutClientsClientIdIndexRouteImport } from './routes/_layout/clients.$clientId.index'
import { Route as LayoutClientsClientIdSettingsRouteImport } from './routes/_layout/clients.$clientId.settings'
import { Route as LayoutClientsClientIdPoliciesRouteImport } from './routes/_layout/clients.$clientId.policies'
import { Route as LayoutClientsClientIdInvoicesRouteImport } from './routes/_layout/clients.$clientId.invoices'
import { Route as LayoutClientsClientIdDocumentsRouteImport } from './routes/_layout/clients.$clientId.documents'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutClientsIndexRoute = LayoutClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => LayoutRoute,
} as any)
const PrintRiskNotesIdRoute = PrintRiskNotesIdRouteImport.update({
  id: '/print/risk-notes/$id',
  path: '/print/risk-notes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutPoliciesPolicyIdRoute = LayoutPoliciesPolicyIdRouteImport.update({
  id: '/policies/$policyId',
  path: '/policies/$policyId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutClientsClientIdRoute = LayoutClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutClientsClientIdIndexRoute =
  LayoutClientsClientIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutClientsClientIdRoute,
  } as any)
const LayoutClientsClientIdSettingsRoute =
  LayoutClientsClientIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutClientsClientIdRoute,
  } as any)
const LayoutClientsClientIdPoliciesRoute =
  LayoutClientsClientIdPoliciesRouteImport.update({
    id: '/policies',
    path: '/policies',
    getParentRoute: () => LayoutClientsClientIdRoute,
  } as any)
const LayoutClientsClientIdInvoicesRoute =
  LayoutClientsClientIdInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => LayoutClientsClientIdRoute,
  } as any)
const LayoutClientsClientIdDocumentsRoute =
  LayoutClientsClientIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => LayoutClientsClientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/clients/$clientId': typeof LayoutClientsClientIdRouteWithChildren
  '/policies/$policyId': typeof LayoutPoliciesPolicyIdRoute
  '/print/risk-notes/$id': typeof PrintRiskNotesIdRoute
  '/clients/': typeof LayoutClientsIndexRoute
  '/clients/$clientId/documents': typeof LayoutClientsClientIdDocumentsRoute
  '/clients/$clientId/invoices': typeof LayoutClientsClientIdInvoicesRoute
  '/clients/$clientId/policies': typeof LayoutClientsClientIdPoliciesRoute
  '/clients/$clientId/settings': typeof LayoutClientsClientIdSettingsRoute
  '/clients/$clientId/': typeof LayoutClientsClientIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/policies/$policyId': typeof LayoutPoliciesPolicyIdRoute
  '/print/risk-notes/$id': typeof PrintRiskNotesIdRoute
  '/clients': typeof LayoutClientsIndexRoute
  '/clients/$clientId/documents': typeof LayoutClientsClientIdDocumentsRoute
  '/clients/$clientId/invoices': typeof LayoutClientsClientIdInvoicesRoute
  '/clients/$clientId/policies': typeof LayoutClientsClientIdPoliciesRoute
  '/clients/$clientId/settings': typeof LayoutClientsClientIdSettingsRoute
  '/clients/$clientId': typeof LayoutClientsClientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/clients/$clientId': typeof LayoutClientsClientIdRouteWithChildren
  '/_layout/policies/$policyId': typeof LayoutPoliciesPolicyIdRoute
  '/print/risk-notes/$id': typeof PrintRiskNotesIdRoute
  '/_layout/clients/': typeof LayoutClientsIndexRoute
  '/_layout/clients/$clientId/documents': typeof LayoutClientsClientIdDocumentsRoute
  '/_layout/clients/$clientId/invoices': typeof LayoutClientsClientIdInvoicesRoute
  '/_layout/clients/$clientId/policies': typeof LayoutClientsClientIdPoliciesRoute
  '/_layout/clients/$clientId/settings': typeof LayoutClientsClientIdSettingsRoute
  '/_layout/clients/$clientId/': typeof LayoutClientsClientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/clients/$clientId'
    | '/policies/$policyId'
    | '/print/risk-notes/$id'
    | '/clients/'
    | '/clients/$clientId/documents'
    | '/clients/$clientId/invoices'
    | '/clients/$clientId/policies'
    | '/clients/$clientId/settings'
    | '/clients/$clientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/'
    | '/policies/$policyId'
    | '/print/risk-notes/$id'
    | '/clients'
    | '/clients/$clientId/documents'
    | '/clients/$clientId/invoices'
    | '/clients/$clientId/policies'
    | '/clients/$clientId/settings'
    | '/clients/$clientId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/clients/$clientId'
    | '/_layout/policies/$policyId'
    | '/print/risk-notes/$id'
    | '/_layout/clients/'
    | '/_layout/clients/$clientId/documents'
    | '/_layout/clients/$clientId/invoices'
    | '/_layout/clients/$clientId/policies'
    | '/_layout/clients/$clientId/settings'
    | '/_layout/clients/$clientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  PrintRiskNotesIdRoute: typeof PrintRiskNotesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/clients/': {
      id: '/_layout/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof LayoutClientsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/print/risk-notes/$id': {
      id: '/print/risk-notes/$id'
      path: '/print/risk-notes/$id'
      fullPath: '/print/risk-notes/$id'
      preLoaderRoute: typeof PrintRiskNotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/policies/$policyId': {
      id: '/_layout/policies/$policyId'
      path: '/policies/$policyId'
      fullPath: '/policies/$policyId'
      preLoaderRoute: typeof LayoutPoliciesPolicyIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/clients/$clientId': {
      id: '/_layout/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof LayoutClientsClientIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/clients/$clientId/': {
      id: '/_layout/clients/$clientId/'
      path: '/'
      fullPath: '/clients/$clientId/'
      preLoaderRoute: typeof LayoutClientsClientIdIndexRouteImport
      parentRoute: typeof LayoutClientsClientIdRoute
    }
    '/_layout/clients/$clientId/settings': {
      id: '/_layout/clients/$clientId/settings'
      path: '/settings'
      fullPath: '/clients/$clientId/settings'
      preLoaderRoute: typeof LayoutClientsClientIdSettingsRouteImport
      parentRoute: typeof LayoutClientsClientIdRoute
    }
    '/_layout/clients/$clientId/policies': {
      id: '/_layout/clients/$clientId/policies'
      path: '/policies'
      fullPath: '/clients/$clientId/policies'
      preLoaderRoute: typeof LayoutClientsClientIdPoliciesRouteImport
      parentRoute: typeof LayoutClientsClientIdRoute
    }
    '/_layout/clients/$clientId/invoices': {
      id: '/_layout/clients/$clientId/invoices'
      path: '/invoices'
      fullPath: '/clients/$clientId/invoices'
      preLoaderRoute: typeof LayoutClientsClientIdInvoicesRouteImport
      parentRoute: typeof LayoutClientsClientIdRoute
    }
    '/_layout/clients/$clientId/documents': {
      id: '/_layout/clients/$clientId/documents'
      path: '/documents'
      fullPath: '/clients/$clientId/documents'
      preLoaderRoute: typeof LayoutClientsClientIdDocumentsRouteImport
      parentRoute: typeof LayoutClientsClientIdRoute
    }
  }
}

interface LayoutClientsClientIdRouteChildren {
  LayoutClientsClientIdDocumentsRoute: typeof LayoutClientsClientIdDocumentsRoute
  LayoutClientsClientIdInvoicesRoute: typeof LayoutClientsClientIdInvoicesRoute
  LayoutClientsClientIdPoliciesRoute: typeof LayoutClientsClientIdPoliciesRoute
  LayoutClientsClientIdSettingsRoute: typeof LayoutClientsClientIdSettingsRoute
  LayoutClientsClientIdIndexRoute: typeof LayoutClientsClientIdIndexRoute
}

const LayoutClientsClientIdRouteChildren: LayoutClientsClientIdRouteChildren = {
  LayoutClientsClientIdDocumentsRoute: LayoutClientsClientIdDocumentsRoute,
  LayoutClientsClientIdInvoicesRoute: LayoutClientsClientIdInvoicesRoute,
  LayoutClientsClientIdPoliciesRoute: LayoutClientsClientIdPoliciesRoute,
  LayoutClientsClientIdSettingsRoute: LayoutClientsClientIdSettingsRoute,
  LayoutClientsClientIdIndexRoute: LayoutClientsClientIdIndexRoute,
}

const LayoutClientsClientIdRouteWithChildren =
  LayoutClientsClientIdRoute._addFileChildren(
    LayoutClientsClientIdRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutClientsClientIdRoute: typeof LayoutClientsClientIdRouteWithChildren
  LayoutPoliciesPolicyIdRoute: typeof LayoutPoliciesPolicyIdRoute
  LayoutClientsIndexRoute: typeof LayoutClientsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutClientsClientIdRoute: LayoutClientsClientIdRouteWithChildren,
  LayoutPoliciesPolicyIdRoute: LayoutPoliciesPolicyIdRoute,
  LayoutClientsIndexRoute: LayoutClientsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  PrintRiskNotesIdRoute: PrintRiskNotesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
